### ISSUE TITLE
Create a Super Admin Role

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#1]

**Comment by RobStallion** [comment]
Make a super admin role in db and only give them access to the signup route.

**Comment by RobStallion** [comment]
with this email: oxl-tr.focusadhd@nhs.net

**Comment by RobStallion** [comment]
user has to be added to the database manually. Added it to my local postgres db to test everything works as expected

**Comment by RobStallion** [comment]
Rest will be done when connecting umbrella.

- [ ] checking to see that the plugs work as expected when coming over from the HL app

**Comment by katyedwards** [comment]
@markwilliamfirth is this one now done and awaiting reply too?

**Comment by markwilliamfirth** [comment]
@katbow is this one part of #90?

**Comment by katbow** [comment]
@markwilliamfirth The super-admin role & plug is complete & does what it is meant to do. The part that still needs doing on this is actually making that user on the deployed site, as it's one we will need to do manually. So I would actually say it's dependent on #50.

**Comment by katyedwards** [comment]
Can a time estimate for this be included in your deployment planning too please.  Thanks @katbow

**Comment by katbow** [comment]
sure thing, it would be back to the t25m estimate.

**Comment by katbow** [comment]
Added to the database on the staging server with the email oxl-tr.focusadhd@nhs.net

**Comment by katyedwards** [comment]
Super user is there and can log in.
