### ISSUE TITLE
message if there is no care team

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#102]
As a service user or carer if there is no care team - I see a message:

## content:
**No staff are associated with your account at this time.**
If you are currently receiving support from the Oxleas ADHD team and would like to use Headscape Focus with your care team email: oxl-tr.focusadhd@nhs.net

See how it was done in Healthlocker here: https://github.com/healthlocker/healthlocker/issues/853

**Comment by katyedwards** [comment]
Yes, looking good
