### ISSUE TITLE
Spike: Host basic phoenix application on azure test environment

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#106]
Have a basic phoenix application that can be found [here](https://github.com/RobStallion/azure_deployment_test)

Deploy the phoenix application to the Azure testing environment that was provisioned by SLaM.

Spike of issue #50.

Following instructions that can be found [here](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md)

**Comment by RobStallion** [comment]
Have currently managed to gain access to the test environment provisioned by SLaM

**Comment by RobStallion** [comment]
Installing dependencies required to run a phoenix application on the VM

**Comment by katbow** [comment]
On [this section](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md#build-the-release) and experiencing this error:

 ![image](https://user-images.githubusercontent.com/1287388/29370170-8200eaf8-829c-11e7-89f6-e182c9e537d2.png)

Investigating now & looking at a similar error from #841 in Healthlocker

**Comment by RobStallion** [comment]
Looking [here](https://github.com/healthlocker/healthlocker/issues/841#issuecomment-313113588) in 841

**Comment by RobStallion** [comment]
@katbow has been able to give me access to the azure testing server provisioned by SLaM

**Comment by RobStallion** [comment]
following those steps I have been able to access the application as root by entering the following command into the command line...

`ssh root@"ip_address"`

**Comment by RobStallion** [comment]
after running the command I am getting a very similar error to the one above, only this time is was a lot later in the build process.

**Comment by RobStallion** [comment]
followed the steps taken [here]() in HL #841 but am currently getting the following error...

![image](https://user-images.githubusercontent.com/15571853/29372584-78bc7e06-82a3-11e7-9866-158bb3dab3f2.png)

Looking into possible solutions now and will update issue with each attempt

**Comment by RobStallion** [comment]
have noticed that the name of server is not what we expected ...
![image](https://user-images.githubusercontent.com/15571853/29372787-0b40a0c2-82a4-11e7-8167-dbdcc4672050.png)

Am going to update the `edeliver/config` to reflect this and try to run the commands again

**Comment by katbow** [comment]
Have it working by *manually* starting the server, which is of course not desirable. Wanted to run through that step though to ensure it still 'works', and that the problem is with something in our edeliver set up

![image](https://user-images.githubusercontent.com/1287388/29375812-486152c6-82ae-11e7-93bb-c283ff0e66f3.png)

**Comment by RobStallion** [comment]
We are currently getting the following issue...

![image](https://user-images.githubusercontent.com/15571853/29375891-9192f74c-82ae-11e7-8b67-46fd4da7f1dc.png)

We followed the instructions found in the ["Production" Phoenix Deployment readme](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md) and when we had errors we looked at [healthlocker issue #841](https://github.com/healthlocker/healthlocker/issues/841#issuecomment-313113588) to see how similar errors were solved in the past. 

@nelsonic Could you please take a look at our current set up and see if there is anything that we may have missed or if there is something that point us in the direction of.

**Comment by RobStallion** [comment]
This is what happens when I `SSH` into the oxleas server...

![image](https://user-images.githubusercontent.com/15571853/29376321-14e6d108-82b0-11e7-9dbe-16674e3f7501.png)

and this is what happens when we log into the HL server...

![image](https://user-images.githubusercontent.com/15571853/29376442-78e80b72-82b0-11e7-9ddc-8b6596504785.png)

The Oxleas server has 
```
*** System restart required ***
```
on every login. Could this be affecting the deployment?

**Comment by reddog** [comment]
@robstallion There was a previous issue regarding setting of environment variables and use of `edeliver`. Could that be an issue here?  See https://github.com/healthlocker/healthlocker/issues/926

**Comment by reddog** [comment]
@robstallion Thanks for the server login messages. It shows that there is a slightly different release of Linux installed 4.4.0.81 vs. 4.4.0.87 plus differences in awaiting updates, particularly some being security updates.

I am not sure - are there any plans in place for updating/supporting these servers?

**Comment by RobStallion** [comment]
@reddog As far as I am aware SLaM are going to be the ones maintaining the servers so I think that they would be better suited to answer that. 

Thanks for picking up on the #926. I've had a look into it and that was a different issue to the one we are currently experiencing but it did prompt me to double check all the environment variables and it doesn't appear they are the problem here.

**Comment by RobStallion** [comment]
After a little more digging it appears that the issue is with the `config/prod.exs` file. 

Found a solution [here](https://elixirforum.com/t/argumenterror-missing-adapter-configuration/3948). After adding this solution to the `config/prod.exs` file I have rerun the following command...
```
mix edeliver build release --verbose
```
Now the build was successful...
![image](https://user-images.githubusercontent.com/15571853/29385419-88840f1c-82cf-11e7-9555-36e42265db81.png)

However it is now printing the following error...
```
mesg: ttyname failed: Inappropriate ioctl for device
```

This appears to stop the rest of the deployment working...
```
mix edeliver deploy release to production
```
![image](https://user-images.githubusercontent.com/15571853/29385490-d1ad3c18-82cf-11e7-8608-ff35aba9fca5.png)

```
mix edeliver start production
```

![image](https://user-images.githubusercontent.com/15571853/29385548-002c3648-82d0-11e7-8acb-a5cc3c2326fe.png)

**Comment by RobStallion** [comment]
looking into this error message...
```
mesg: ttyname failed: Inappropriate ioctl for device
```

**Comment by RobStallion** [comment]
After briefly looking into the error above, `ioctl` appears to be an issue with `unix` and therefore is possibly something that needs to be fixed on the server itself.  

@reddog @katyedwards We are still looking into this but as Stuart is away from tomorrow could you please double check with SLaM to see if this is may be related to the server setup.

**Comment by reddog** [comment]
@RobStallion This is probably a user profile/term setup issue.

This `ioctl` error has been shown a few times in your screenshots.  Is it actually stopping anything from working or is it just reporting something that *should* be fixed?  If it doesn't really matter, can we leave it for now?

Does @katbow have the same issue (if not, could it be something on your local machine, in which case, could that be fixed later and we use @katbow's laptop for now)?

If it does need fixing, can you compare your `.profile` files on the (working) HL server and (erroring) Oxleas server - are there any differences?

@katbow Gave an example where a manual start worked, see https://github.com/healthlocker/oxleas-adhd/issues/106#issuecomment-322838397  Can that be used for now?  What would be the downside of sticking with that for now?

Have you had any input from @nelsonic as per your previous request?

**Comment by RobStallion** [comment]
@reddog We have seen that the error message appears multiple times in the screenshots. Was part of the reason that we posted them all. It is something that needs to be fixed as it is stopping the deployment from working. 

@katbow is having the same issue as this is not an error with our local machines, it is an error with the server that we are both `SSH`ing into. (Have tried on both laptops just to be clear)

The .profile appears to be correct as we mentioned [here](https://github.com/healthlocker/oxleas-adhd/issues/106#issuecomment-322877879) in response to your comment last night. 

Working with a manual start was so that we could make sure that the error was not to do with the elixir code base. This is not a realistic solution as it would rely on one of us having our laptops on constantly running the project and would not reflect a real world app. In other words, it wouldn't really be a deploy, it would just be us running the project on a VM the way we do on our local machine.

**Comment by katbow** [comment]
We deployed with a simple phoenix app without ecto. The same message came up, but also with an `ok`. 

![image](https://user-images.githubusercontent.com/1287388/29408210-408e4d7e-833f-11e7-87da-f923e17366bc.png)

We were able to run the site this way. So it seems that particular message is not actually the problem, and it is still something with the configuration involving ecto.

**Comment by reddog** [comment]
@katbow Looks like a useful test.

So, although annoying, can leave the `ioctl` config correction for now?

What are the steps to test a basic app with `ecto` present?

Are you running a Vagrant machine locally?  Are there any issues along the lines of https://github.com/healthlocker/healthlocker/issues/856 or https://github.com/healthlocker/healthlocker/issues/864 ?

**Comment by katbow** [comment]
@reddog no because for #856 that was deploying to heroku (because mssql was not available on heroku and we aren't using either heroku or mssql for this application), and for #864 we are not using vagrant. We are looking into the steps we need to take with ecto.

**Comment by RobStallion** [comment]
Have managed to successfully deploy the application with ecto. Needed to fix error with db config in `config/prod.exs`. 

Next step is #107 which @katbow has already began work on.
