### ISSUE TITLE
Deploy basic umbrella app

### ISSUE THREAD

**Issue by katbow** [healthlocker/oxleas-adhd#107]
Linked to #106, #50 

The goal of this & #106 is for @RobStallion & I to go through and understand the *extensive* documentation written by Nelson. 

This issue is longer than #106, as this is being down with a different application set up (umbrella vs regular), which has not yet been done by either ourselves, or Nelson. Because of this, differences in this process are not yet documented, and will need to be figured out through the deployment process.

It will involve:
* Configure edeliver (T2h)
* Setting up the azure server for deploying app(T2h)
* Build with edeliver - (T4h). This is a longer step as it is one we are currently experiencing most problems with in #106.

**Comment by RobStallion** [comment]
basic phoenix umbrella has been created [here](https://github.com/katbow/umbrella_deployment)

**Comment by katbow** [comment]
Set up edeliver & distillery in the apps/phoenix_app section but had the following error:

![image](https://user-images.githubusercontent.com/1287388/29410292-d6287136-8347-11e7-9360-8eb88ec2ec4b.png)

According to [this guide](https://medium.com/@brucepomeroy/deploying-an-elixir-umbrella-project-using-distillery-and-edeliver-b0e8528569e3) we need to instead set up edeliver & distillery in the root of the umbrella app (which is what our initial thought was).

**Comment by katbow** [comment]
Still have the same error. Moving the `package.json` & the `brunch-config.js` from the `phoenix_app` to the root.

**Comment by katbow** [comment]
node modules installed this way. Release was built, however had other errors, shown in the 2 images below.
![image](https://user-images.githubusercontent.com/1287388/29410770-01e843d0-834a-11e7-801d-369fcfbdffe3.png)

![image](https://user-images.githubusercontent.com/1287388/29410777-0bd51c2e-834a-11e7-8fbf-a9d11b6cd41f.png)

Looking at setting the `RELEASE_VERSION` environment variable on the server.

**Comment by katbow** [comment]
A `RELEASE_VERSION` environment variable was not necessary. Instead, the extra line in the `.deliver/config` file that was added from the [link in this comment](https://github.com/healthlocker/oxleas-adhd/issues/107#issuecomment-323039393) was changed from `RELEASE_DIR="$BUILD_AT/apps/$APP/rel/$APP"` to `RELEASE_DIR="$BUILD_AT/rel/$APP"`. It was changed to this because the initial red error in the image from the above comment pointed to folders & files that did not exist.

After changing this we have this:

![image](https://user-images.githubusercontent.com/1287388/29411658-b964f9ec-834d-11e7-888d-f9ddbe21f6ba.png)

Which *looks* like it has built successfully, but we are missing the `ok`. So when we try to go to the site, it doesn't work.

Going to remove this section entirely from the config because of documentation found [here](https://github.com/edeliver/edeliver/wiki/Umbrella-Projects).

**Comment by katbow** [comment]
We removed the release version & it deployed, however it's not finding `priv/static` files. This means JS & CSS files don't load, so the deployed site looks like this:

![image](https://user-images.githubusercontent.com/1287388/29414473-b4fcc2ae-8357-11e7-9c4e-55e86f0264f8.png)

**Comment by katbow** [comment]
we've been reading up on documentation from edeliver & distillery for umbrella apps specifically to see if there was anything about loading the static files. We couldn't find anything specific in the documentation for this, however @RobStallion thought we should change the `brunch-config.js` file to indicate where we want to build the static files to.

We changed it to watch the static folder from the `phoenix_app`, as it was previously attempting to find (non-existent) static files within the root of the application. 

![image](https://user-images.githubusercontent.com/1287388/29420101-f019a422-8368-11e7-9f4f-4c510e2697c4.png)

We also updated where it compile files to, which is now the `priv` folder in `phoenix_app`. 

![image](https://user-images.githubusercontent.com/1287388/29420079-e4adb952-8368-11e7-90c6-fd7eedea3a0e.png).

This loaded the styling after deploying!

![image](https://user-images.githubusercontent.com/1287388/29420208-3dfbed6c-8369-11e7-9610-ecefb9c56442.png)

However it was sometimes not loading locally, and looked like the image in the above comment. To ensure this was actually working as expected with the deploy, we added some extra css, removed the app from the server & redeployed with the styling change.

![image](https://user-images.githubusercontent.com/1287388/29420250-5b94e1a8-8369-11e7-85f2-8b373b7b5ff1.png)

The css change came in, however the assets were not found (the Phoenix image at the top). I think this will need to be included explicitly as well to be watched.

**Comment by katbow** [comment]
Added in 
![image](https://user-images.githubusercontent.com/1287388/29420792-fa22e594-836a-11e7-9607-e4a3095d4da2.png)

which will take the static assets from within `phoenix_app` and compile them to the `phoenix_app/priv` folder. Now we have...

![image](https://user-images.githubusercontent.com/1287388/29420884-44430686-836b-11e7-8235-4e66b371b6ee.png)

which is just what we're looking for 👌 .

We want to take some time to investigate why this is not working as expected locally, which will give us more confidence that this is the *correct* solution.

**Comment by reddog** [comment]
@katbow Looks like your tests are giving good results.

CSS working on Azure vs. not when viewed locally - couldn't be something as simple as browser cached CSS could it?  It could well be that the webserver configurations for your local machine and Azure could be configured with different content expiry settings (although you do, of course, develop locally, however not in a *deployed* sense).

**Comment by katbow** [comment]
It was a difference in the configuration for dev vs prod. Changed this section:

![image](https://user-images.githubusercontent.com/1287388/29422067-f0957d30-836e-11e7-8454-80aa5d2877aa.png)

It was looking for the `node_modules` in `apps/phoenix_app/node_modules` even though they had all been move to the root. It wasn't able to compile the assets locally with brunch since it couldn't find the npm package for it. 

There's one last check we're doing with the `elixir_app`, then this will be good to close off 👍 .

**Comment by katbow** [comment]
Alright, all good! The final version of the set up is [on this repo](https://github.com/katbow/umbrella_deployment).

We'll need to consider that we have more static assets & of different types in oxleas app. This seemed to be a bit of a sticking point today, which we fixed for the file types & folders we had in the basic app. However something to still be mindful of & the fact that oxleas app is much more complex as a whole.
