### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#114]
![headscape logo favicon 16px-02](https://user-images.githubusercontent.com/25012688/29556536-0c041664-871e-11e7-8910-860c205e8767.png) 16px
![headscape logo favicon 32 px-03](https://user-images.githubusercontent.com/25012688/29556533-09615390-871e-11e7-8cd2-b101064dbb97.png) 32px

**Comment by markwilliamfirth** [comment]
Just a note to say that this was not in the original scope and was added later - @Cleop will complete this if there is still time at the end of the sprint, but it is not guaranteed

**Comment by katyedwards** [comment]
Have hopefully done this... awaiting review.

**Comment by SimonLab** [comment]
@katyedwards I've just merged your PR which add the new image, however you might need to test if it's properly loaded, you might need to update the url in the templage:
https://github.com/healthlocker/oxleas-adhd/blob/7952425eea19a1c8bdf31d642c10dbcbeeb5b7e1/apps/healthlocker/web/templates/layout/app.html.eex#L15
