### ISSUE TITLE
errors that came up after healthlocker deployment

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#116]
- [x] https://github.com/healthlocker/healthlocker/issues/905
Was to do with sending emails from the site. Was initially an error with SLaM's setup of the virtual machine.

- [x] https://github.com/healthlocker/healthlocker/issues/894
Was also to do with sending emails from the site. This one was our side.

- [x] https://github.com/healthlocker/healthlocker/issues/887
This issue came up when you entered some tracking data but not all 3, for example, just enter diary for a day and then go to /tracking-overview

- [x] https://github.com/healthlocker/healthlocker/issues/885
Have to log in as a user to check that this works. Can log in as Robert MacMurray. Same details as in Healthlocker. Then go to a page that loads a static text file, such as /sleep-tracker/new.

- [ ] https://github.com/healthlocker/healthlocker/issues/915
Messages not submitting. 
**Has occurred again - needs fixing for Oxleas**

**Comment by katyedwards** [comment]
Thanks @RobStallion is Oxleas fully deployed and ready for us to start testing and closing issues now?

**Comment by RobStallion** [comment]
@katyedwards yes you can start closing issues now.

**Comment by katyedwards** [comment]
Thanks @RobStallion can you slack us login details for the super admin so we can create accounts for ourselves to use for testing.   Thanks!

**Comment by katyedwards** [comment]
Messages aren't submitting #125

**Comment by katyedwards** [comment]
Closing this as messages not submitting has been moved into a new issue.  Everything else seems to work fine.
