### ISSUE TITLE
Super User view of which staff are assigned to SU

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#124]
When logged in as super admin:

If you click on an SU to view their details, the staff members become unticked.  

If you click the browser back button _without_ clicking save then the original staff members remain assigned (but you can't see who it is)

If you click Save then it removes all staff previously assigned.

So if the Super User clicks to view and SU they cannot tell who was assigned previously, and if they want to add an additional staff member they would have to re-tick all the others too.

This may be a bit unclear.

**Comment by ghost** [comment]
Resolved by #179
