### ISSUE TITLE
Collection of Documentation for Setting up Oxleas

### ISSUE THREAD

**Issue by markwilliamfirth** [healthlocker/oxleas-adhd#126]
Created by myself by request from @reddog (https://github.com/healthlocker/oxleas-adhd/issues/108#issuecomment-324381692)

**As a** CTO of Mindwave Ventures
**I would like** a single place where I can see all the documentation for setting up a new Oxleas environment
**So that** I can use this to set up Oxleas in future at other places

This includes documentation for:
- [ ] The Azure deployment process
- [ ] Setting up SSL
- [ ] Setting up nigjnx
- [ ] Setting up AWS SES

@katbow @RobStallion please could you link the relevant updated documents here as and when they are done?

**Comment by markwilliamfirth** [comment]
@reddog to update this issue to reflect his requirements

**Comment by markwilliamfirth** [comment]
@reddog please could you close this issue if it's no longer required due to (https://github.com/healthlocker/oxleas-adhd/issues/138) or please could you confirm below that this is correct and this meets your requirements

**Comment by reddog** [comment]
Closing as https://github.com/healthlocker/oxleas-adhd/issues/191 kicked off getting documentation created which is is available and is being added to at https://github.com/healthlocker/oxleas-adhd/blob/master/deployment_and_ssl_doc.md
