### ISSUE TITLE
nginx Installation, Configuration and Setup

### ISSUE THREAD

**Issue by markwilliamfirth** [healthlocker/oxleas-adhd#127]
Linked to https://github.com/healthlocker/oxleas-adhd/issues/49 https://github.com/healthlocker/oxleas-adhd/issues/94

@katbow @RobStallion please can you provide a time estimate

Time estimate should include:

- [ ] Time necessary to review implementation documentation

- [ ] Installation, Configuration and Setup of nginx to Oxleas

**Comment by RobStallion** [comment]
closed in favour of #94
