### ISSUE TITLE
AWS SES configuration

### ISSUE THREAD

**Issue by markwilliamfirth** [healthlocker/oxleas-adhd#130]
@katbow @RobStallion please can you provide a time estimate

Time estimate should include:

- [ ] Time necessary to review implementation documentation

- [ ] Installation, Configuration and Setup of AWS SES on Oxleas

**Comment by katbow** [comment]
#32 & #33 need to be done for this. Shouldn't be any other installation/set up as it's already completed within app. T25m for both of those together

**Comment by katyedwards** [comment]
@katbow As #32 and #33 have been done - can this issue be closed?  (just waiting for Oxleas to confirm they have received the feedback email, then will close that).

**Comment by katbow** [comment]
Yep if you have confirmation from them that they received the email then it can be closed

**Comment by katyedwards** [comment]
Ok thanks - I'll wait til they have confirmed then will close both.

**Comment by katyedwards** [comment]
Have received confirmation!
