### ISSUE TITLE
Steps required to complete project installation

### ISSUE THREAD

**Issue by reddog** [healthlocker/oxleas-adhd#138]
Please list all technical functional components required in order to complete the project installation such that:

1.  the installation is similar in nature to SLaM's Healthlocker installation in terms of technical components
2.  the project, namely Oxleas' Healthlocker implementation - this (and associated) repos, are in a complete state for client use.

As examples, but not necessarily an exhaustive list, this should include nginx, SSL, etc.

For each technical component, please list:

- [ ] technical functional component
- [ ] issue covering this item
- [ ] time estimate for completion of this issue
- [ ] assignees
- [ ] when this issue is scheduled to be completed.

**Comment by markwilliamfirth** [comment]
@katbow @RobStallion please could you provide a time estimate?

**Comment by markwilliamfirth** [comment]
@reddog please indicate the prioritisation for a time estimate for this compared with other issues

**Comment by reddog** [comment]
@markwilliamfirth Getting to a complete project set up ready for end user access is a *key goal* for this sprint.  As such I would imagine that the information requested here is actually listed somewhere else (maybe just in people's heads?).  How long will listing it here take?

**Comment by reddog** [comment]
Completed with documentation detailed in https://github.com/healthlocker/oxleas-adhd/issues/191
