### ISSUE TITLE
Clinician: Input medication notes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#15]
+ [x] As a clinician, I can write what medication a service user is taking, dosage and other info.
+ [x] As a clinician, I can edit what medication a service user is taking, dosage and other info.
+ [x] As a clinician, I can click save.
+ [x] As a clinician, I can read some static FAQs about accessing medication from the ADHD team. (so that I can see what info is supplied to my patients)

<img width="285" alt="screen shot 2017-07-11 at 14 48 09" src="https://user-images.githubusercontent.com/25012688/28071485-ff620688-6647-11e7-8686-f68c1e45e316.png">

**Comment by iteles** [comment]
1 day:
  + Create model for schema
  + Create database schema (similar to diary)
  + Create form
  + Create routes for form
  + Making sure data is available in form when we go back in
  + FAQs (static data)
  + Showing timestamp

Multiple clinician functionality: 
+ Add in functionality to save user who edits medication and display in this view: 2 hours (lower priority) - new issue to be created to split this out

**Comment by iteles** [comment]
Removed from Sprint 1 milestone as discussed with @dbower and @katyedwards on 18th July due to a miscounting up of days in the milestone:

**Comment by MollieCourtenay** [comment]
##content

##My medication 
 
**What medication do I take for my ADHD?** 
Who prescribes this? 
 
 
**How much/ what dose? 
 
How often and when? 
 
 
Other medication that I take?** 
Who prescribes this? 
 
 
**My allergies:** 
 
 
**What medication have I taken in the past for my ADHD?** 
Why did this change? 
 
 
**Most recent update:** 
 
[ clinician name, role ] [ DD/MM/YY ] [ 18:47 ] 
 
 
 
 
##Medication FAQs (centered)
 
**Who do I get my prescriptions from?** 
The ADHD team usually prescribe your medication for the first 3 months or so whilst we are getting the dose right for you. Once we get to a dose that appears to work for you, will discuss with you about going on to "Shared Care" with your GP, which means your GP will prescribe the medication and you can pick it up from them.  
 
**If I get my prescriptions from the ADHD team, how much notice do I have to give?** 
You need to let the ADHD team know that you need a prescription at least 5 working days before you run out of medication. You can let them know by [sending a message](/https://www.healthlocker.uk/care-team/rooms/??). 
 
Put a note on your mobile phone diary or calendar to remind you when you need to order your next prescription. See more [#Tips](/tips).  
 
**How long are prescriptions valid for?** 
Prescriptions of controlled medications, like Methylphenidate, including extended-release  formulations of it like Medikinet XL, Concerta XL or Equasym XL, are only valid for 28 days from the date they were written so you need to take them to a pharmacy before the end of that period.  
 
Prescriptions for medications that are not controlled drugs are valid for 6 months from the date of the prescription. These includes Circadin and Atomoxetine which are prescribed by the ADHD team.  
 
**What do I do if I get side effects from the medication?** 
Let the ADHD team know that you think you are getting side effects from the medication and they can discuss with you what to do about it. The ADHD team is available Monday to Friday 9-5pm, so outside of these hours, if you are unwell and experiencing symptoms that might be related to medication, particularly chest pain or your heart racing in your chest, contact your local out-of-hours GP service or visit your local [A&E](http://www.nhs.uk/Service-Search/Accident-and-emergency-services/LocationSearch/428) to get checked out. 
 

_______ 
END

**Comment by katbow** [comment]
The feature building for this is done (awaiting review). However, the route is currently 'open' and can be accessed by anyone with the url. The next step is to make this accessible to only the staff for that user. This will be done after the clinician connection/relationship table is completed.

**Comment by MollieCourtenay** [comment]
+ [ ] Please call this 'Medication notes' so Edit Medication notes /  New Medication notes

**Comment by katyedwards** [comment]
@Cleop Sorry - the screenshot wasn't accurate.

We need additional text boxes for:

- [ ] What medication do I take for my adhd?

- [ ] Other medication I take:

- [ ] What medication have I taken in the past for my ADHD?

Right now you can fill in details _about_ the medications, but there is no where to fill in what the medication actually is!

And same viewable text boxes on the SU view #16 

@MollieCourtenay I assume this is something that needs updating before going live because I think it'll be very confusing to leave as it is, but tagging you in case you think we can work round it through training staff to include additional info in existing boxes.

**Comment by katyedwards** [comment]
@MollieCourtenay done apart from text colour - is it ok?

**Comment by katyedwards** [comment]
Copy colour moved into #148 So good to close
