### ISSUE TITLE
Reset Password Link - to subdomain address, not IP address

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#155]
- [x] Update the reset password link so it contains the subdomain and takes you to the subdomain address.

Currently: http://**51.140.117.78**/password/hS8Di01CwBQ50fycH0OsSPZr7NsezKnLxlkzv2d7hlkiCGdY/edit

Should be:
http://**focus.headscapegreenwich.co.uk**/password/hS8Di01CwBQ50fycH0OsSPZr7NsezKnLxlkzv2d7hlkiCGdY/edit   (or something like that, but a string that will work!)

Being taken to http://51.140.117.78/login once you have reset the password might be confusing or concerning for some people.

- [x] Update subject line -  so HeadScape has a capital S.

**Comment by reddog** [comment]
Will need to use `https` for the link once #94 is complete.

**Comment by SimonLab** [comment]
An environement variable will be used to determine the hostname: We could have define the hostname in the production config file: https://github.com/healthlocker/oxleas-adhd/blob/bf0674f4d3cf73f00d0282a6c07a20d4e5671413/apps/healthlocker/config/prod.exs#L14 however this doesn't allow us to define a different hostname for the staging and production environment.

**Comment by nelsonic** [comment]
@SimonLab does the server need to be restarted to use the Environment Variable?

**Comment by SimonLab** [comment]
@nelsonic the sever doesn't need to be restarted, the environment variables have been added to the servers and we use the command ```source``` to load them

**Comment by nelsonic** [comment]
@SimonLab thanks for confirming. ✅

**Comment by katyedwards** [comment]
Looks good!
