### ISSUE TITLE
Remove vertical black line in Clin view of goals and coping strats

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#157]
+ [ ] remove line

**Comment by RobStallion** [comment]
@MollieCourtenay @katyedwards Could you please provide me with login details for one of the test clinicians you have been using where you have been getting this issue? Feel free to send them over in a slack message if you prefer.

**Comment by reddog** [comment]
Would a screenshot help?

@MollieCourtenay or @katyedwards Can you please provide a screenshot?  (not sure if Rob will still need login details thereafter?)

**Comment by MollieCourtenay** [comment]
@robstallion the vertical divider line is not an error. 
It is just a preference of the Oxleas team not to have it as part of the styling on that page as SLaM do.

**Comment by MollieCourtenay** [comment]
![img_2791](https://user-images.githubusercontent.com/25012688/30200461-e8412574-946e-11e7-83da-9a3b6bee899f.PNG)

**Comment by RobStallion** [comment]
Ahh sorry that way my misunderstanding. Thanks for clearing that up for me @MollieCourtenay 👍

**Comment by MollieCourtenay** [comment]
@RobStallion no worries :)
 I've done it. @reddog showed me how.

**Comment by katyedwards** [comment]
Fabulous!
