### ISSUE TITLE
set up Google Analytics

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#158]

**Comment by reddog** [comment]
@katyedwards Has a Google Analytics account been created for this?  Do we have a `tracking ID`?

Who is going to *own* the Google Analytics account?

**Comment by reddog** [comment]
@MollieCourtenay Would I be right in saying that this is with you at the moment?

**Comment by MollieCourtenay** [comment]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-106165229-1', 'auto');
  ga('send', 'pageview');

</script>

Set up for: 
https://focus.headscapegreenwich.co.uk

@reddog

**Comment by reddog** [comment]
@iteles Was there a problem with that script?

**Comment by iteles** [comment]
@reddog I think I had a brain block - wanted to remove just to have a think about whether there were any implications around others using the token to be on the safe side (I had just transferred to a google doc I was about to share), but having thought about it, there are no issues and it will be available in the code for reference anyway. 👍
