### ISSUE TITLE
SU: View medication notes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#16]
+ [x] As a service user, I can read medication info.
+ [ ] As a service user, I can see who from my care team was the last to update the note.
+ [x] As a service user, I can see a timestamp for the last time the medication notes were updated. 
+ [x] As a service user, I can read some FAQs about accessing medication from the ADHD team.
+ [x] As a service user, I am invited to message my care team about my medication (add link to messages).

<img width="283" alt="screen shot 2017-07-11 at 11 09 49" src="https://user-images.githubusercontent.com/25012688/28063615-92f7776c-6629-11e7-9f6c-6a2e54551f67.png">

**Comment by katbow** [comment]
For this one:
> As a service user, I can see a timestamp for the last time the medication notes were updated.

Since it coincides with adding the timestamps for #15, and this was marked as lower priority in this comment: 
https://github.com/healthlocker/oxleas-adhd/issues/15#issuecomment-315719225, should this also be moved to a new issue as lower priority? @MollieCourtenay

**Comment by MollieCourtenay** [comment]
@katbow I guess that makes sense yes. 
missed that that had been de prioritised :(

I'll make a note to make new issues for these.

**Comment by MollieCourtenay** [comment]
Oh from those commits - it does look like you have managed to work on it? @katbow

**Comment by katbow** [comment]
@MollieCourtenay I have the most recently updated for time. This is a field that's in the database automatically, so I just displayed it. Saying who updated it would be a new field to add & display so that's the part in particular that's not yet been worked on. 

Adding the staff name is first on my list after I get other necessary issues completed 👍 .

**Comment by MollieCourtenay** [comment]
+ [ ] add some padding above the new medication icon. So it is not so close to the diary button.
<img width="301" alt="screen shot 2017-08-22 at 17 12 35" src="https://user-images.githubusercontent.com/25012688/29575690-3350d9f2-875d-11e7-814d-a4239646d465.png">

**Comment by katyedwards** [comment]
Same notes as #15 

We need additional viewable text boxes for 

- [ ] What medication do I take for my adhd?

- [ ] Other medication I take:

- [ ] What medication have I taken in the past for my ADHD?

**Comment by MollieCourtenay** [comment]
the links in the medication FAQs need the aqua flex wrap

**Comment by MollieCourtenay** [comment]
+ [ ] it would be best if the text was not this new blue colour - I think another assumption from the hacks but ideally they would just be the dark blue.

**Comment by katyedwards** [comment]
@MollieCourtenay That last comment, do you mean the headings text  - what meds am I taking etc?

**Comment by katyedwards** [comment]
Copy colour moved into new issue - #148

**Comment by katyedwards** [comment]
Ok to close
