### ISSUE TITLE
remove the duplicated tip 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#161]
+ [ ] remove one.
<img width="244" alt="screen shot 2017-09-01 at 17 07 58" src="https://user-images.githubusercontent.com/25012688/29978222-25396144-8f38-11e7-8432-1d7459cbebe2.png">

**Comment by katyedwards** [comment]
Sorry that'll need @RobStallion - we can't edit tips, only stories

**Comment by katyedwards** [comment]
Database will be clear when it deploys to live - can we live with a duplicated tip remaining on the test site?
@MollieCourtenay

**Comment by MollieCourtenay** [comment]
I guess so yes. @katyedwards 
I'd prefer to get rid of it at some point though as it was noticed by client.

**Comment by reddog** [comment]
@RobStallion Can we please confirm what is required for this change?  Is it just a database entry deletion or is something else required?  Would all such database deletions require 25 minutes?

**Comment by RobStallion** [comment]
No that is just the smallest time stamp that was there. I completed this while I was writing the readme
