### ISSUE TITLE
Super Admin User - edit the email of the Service User account

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#163]
## Acceptance Criteria:

- [x] As a Super Admin I can log into the portal, view a Service User and see their email address is in a free text box.

- [x] As a Super Admin I can change the email address in the free text box and click save to update the email address in the database.

- [x] This will change the email address a user must use to login

**Comment by katbow** [comment]
Note on this and related to #179. Since there would now be multiple things to access/edit in relation to a service user, it may be useful to display a menu/icons when clicking on a service user. One each for Edit Teachers, Edit Clinicians, Edit Service User Details.

**Comment by katbow** [comment]
Estimate is for creating the edit form & saving the edited information, UI for accessing this section is not included yet in estimate.

**Comment by Cleop** [comment]
To be kept in this sprint in case #221 is not ready to work on in time, not necessarily going to be completed this sprint but here as the next thing to work on if #221 isn't ready.

**Comment by katyedwards** [comment]
Seems to be working great! Thanks!
