### ISSUE TITLE
Oxleas HL website down - just get the nginx welcome page

### ISSUE THREAD

**Issue by reddog** [healthlocker/oxleas-adhd#164]
Visit http://focus.headscapegreenwich.co.uk/

All that is shown is the nginx welcome page:

Issue reported by a member of the Oxleas team whilst they were trying to undertake some testing.

![image](https://user-images.githubusercontent.com/151362/30020852-4977f2a6-915d-11e7-9323-f7fb4cbf4a67.png)

Can the site please be brought back up?

Has the Oxleas site been taken down intentionally?  If so, whilst what is being done and for roughly how long?

If not intentionally, can we try and understand why it is down on this occasion?

**Comment by RobStallion** [comment]
@reddog Sorry about that. I took the site down. I was checking the nginx settings on the server over the weekend. I can put it back up for you in a few minutes. I didn't realise that there was going to be testing today so again, sorry about that. Hope it hasn't caused too much inconvenience.

I made a comment [here](https://github.com/healthlocker/oxleas-adhd/issues/94#issuecomment-326944684) which I think links directly to this issue. Could you please take a look at it when you have a moment. Thanks

**Comment by RobStallion** [comment]
Site is now back up

![image](https://user-images.githubusercontent.com/15571853/30025760-d9c8f5da-9171-11e7-9433-935e0fcc9db3.png)

**Comment by reddog** [comment]
@RobStallion Thanks for putting the site back up, and thanks for your investigations on nginx setup - were you able to find what you required?

I don't think that anyone here thought that the site would be down.  I think that's really where the issue comes from.

If you do need to take the site down could you maybe raise an issue so that we can all see what's happening?  And then put the site back as soon as possible thereafter?

In terms of once a site has gone live (which Oxleas hasn't) - it probably shouldn't be taken down without prior confirmation.

**Comment by reddog** [comment]
Confirmation that sites are going to go down has been discussed.  Closing old issue.
