### ISSUE TITLE
Bring live site up to same configuration as test site

### ISSUE THREAD

**Issue by reddog** [healthlocker/oxleas-adhd#168]
Live site is at http://focus.headscapegreenwich.co.uk/ with IP address `51.140.116.95`

Test site is at http://test-focus.headscapegreenwich.co.uk/ with IP address `51.140.117.78`

From a user's perspective, the *live site* is currently showing the nginx welcome message:

![image](https://user-images.githubusercontent.com/151362/30058028-1c9ffcf4-9231-11e7-80c8-9c38fb2ca9df.png)

The *test site* is currently showing the deployed app:

![image](https://user-images.githubusercontent.com/151362/30058118-7ed76ace-9231-11e7-8574-f118a3aa1ad6.png)

Requirements:
- [x] list setup differences between live and test sites
- [x] provide time estimates to complete those tasks

Acceptance criteria:
- [x] live site should have same technical setup steps completed as test site

**Comment by reddog** [comment]
Requires previous completion of:

https://github.com/healthlocker/oxleas-adhd/issues/94
https://github.com/healthlocker/oxleas-adhd/issues/125

**Comment by RobStallion** [comment]
Steps to complete 

- Install software needed to run app (T1h)
  - [x] nginx
  - [ ] node
  - [ ] erlang
  - [ ] elixir 
  - [ ] postgres
  - [ ] hex
  - [ ] phoenix

- [ ] Create an SSL certificate (T2h)

- [ ] Update nginx config (T1h) (cannot be completed until steps above are done)

**Comment by reddog** [comment]
@RobStallion I have created a new issue #193 to ensure that SSL certificates are set to auto-renew (otherwise we will effectively loose access after 90 days).

I am not sure if you would want to complete this on test first before implementing on the live site?

Please do let me know if you'd like any further information on this configuration.

**Comment by RobStallion** [comment]
@reddog could you please add this as a new comment next time rather than edit an existing comment if you have a question

- [ ] Setup auto-renewing SSL certificates, see #193 (time ??)

**Comment by reddog** [comment]
@RobStallion Sure - I added it to the list so that it could be seen it was a step (for now and for referencing back) and I also made a separate comment.  Sorry if I didn't explicitly reference the change to the list in my separate comment.

**Comment by RobStallion** [comment]
Currently having an issue with the following step
`get test app running on server using edeliver`

The app is on the server and can be run if I do it manually by `ssh`ing into the server, `cd`ing to `/home/oxleasadmin/azure_deployment_test/builds` and running the `mix phoenix.srever` command.

![image](https://user-images.githubusercontent.com/15571853/30159870-0cd682d8-93c2-11e7-906a-5701423766cf.png)

But when I run the `mix edeliver start production` command from my local machine it does not start and I get no obvious errors or indication that it hasn't worked. 

![image](https://user-images.githubusercontent.com/15571853/30159981-74775a52-93c2-11e7-9334-12b9116cfaee.png)

**Comment by RobStallion** [comment]
Have not found any errors that point to what this could be yet. Only differences between running the app with `mix edeliver start production` and doing it manually by going into the server is that the `mix` command runs the app in `prod` mode. 

Next steps
Check the differences between `prod.exs` and `dev.exs`
Make sure all environment variables are entered and correct

**Comment by RobStallion** [comment]
`PORT` was missing from the environment variables. Working now...

![image](https://user-images.githubusercontent.com/15571853/30160802-f31a175c-93c5-11e7-889c-243ed0097cf2.png)

![image](https://user-images.githubusercontent.com/15571853/30160811-03ab3880-93c6-11e7-86e7-069994b48d63.png)

**Comment by reddog** [comment]
@RobStallion Good spot with the missing `port` setting.

I think we've seen this before.  Is there a way we can fix this from happening again?

It would also be good to note that the `START DONE!` message is a little (very?) misleading as it hasn't actually started unless there is an `ok` showing before that.  We've seen this before as well.

**Comment by RobStallion** [comment]
@reddog @katyedwards I am in the process of getting the certificate for the live server but I need to enter an email address ...
![image](https://user-images.githubusercontent.com/15571853/30163125-b1108b2a-93cf-11e7-9dc3-58528894ca76.png)

Which email would you like me to use for this? Feel free to send me this over slack if you prefer

**Comment by katyedwards** [comment]
I would think it should be the Oxleas one - will slack you...

**Comment by reddog** [comment]
@RobStallion #193 has been removed from the list of tasks for this issue (see https://github.com/healthlocker/oxleas-adhd/issues/168#issuecomment-327748143 ).  Will this be completed separately?

**Comment by RobStallion** [comment]
@reddog #193 was not originally part of this issue and is not something that we discussed when were planning this mini sprint. During the stand up yesterday it was agreed that I would work on #168, #187 and #4 in that order and then after that look at @katyedwards PRs and add time estimates to the remaining issues. 

If you want #193 to be completed then I can do that but it may impact other things being completed.

**Comment by reddog** [comment]
@RobStallion You are of course right - #193 has not been thought of before - it probably should have been, and hence I raised it as soon as I did.

Since this issue concerns provisioning a new instance (the live site), I have added in #193 here since it **will** be required within the next 90 days at least.

The fix for #193 is adding a cronjob item.  Of course it would be very useful to get your time estimate for this.

**Comment by reddog** [comment]
Visiting https://focus.headscapegreenwich.co.uk/ (live site) shows `Test phoenix application`

![image](https://user-images.githubusercontent.com/151362/30166091-2cfc6e2a-93da-11e7-8b8f-9d10602778b6.png)

Is the Oxleas HL app not supposed to display?

**Comment by RobStallion** [comment]
This issue was for bringing the live site up to same configuration as test site. #187 is for the deployment

**Comment by iteles** [comment]
@reddog That is covered in https://github.com/healthlocker/oxleas-adhd/issues/187, whereas this issue is around configuration.

**Comment by iteles** [comment]
@RobStallion Snap 😉

**Comment by reddog** [comment]
@RobStallion Thanks for clarifying that - I didn't have that distinction in my mind.

Would you be able to provide the steps required for #187?

**Comment by reddog** [comment]
@iteles I think my wording wasn't clear - I will try harder next time

**Comment by katyedwards** [comment]
Seems ok to me!
