### ISSUE TITLE
Clinician: input About me form

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#17]
+ [x] As a clinician, I can write into / edit a service users About me form.
+ [x] As a clinician, I can see who from the care team made the last updates and when.
+ [x] As a clinician, I can see when the About me form was last updated by the service user.
+ [x] As a clinician, I can save my edits.
+ [x] use normal Healthlocker dark blue, not this other blue.

<img width="374" alt="screen shot 2017-07-11 at 11 04 14" src="https://user-images.githubusercontent.com/25012688/28063335-bc719556-6628-11e7-9767-820fe4952e47.png">

**Comment by MollieCourtenay** [comment]
what happens if this is updated at the same time?

**Comment by iteles** [comment]
2 hours of this is for the 'Most recent update' section which can be deprioritised if required as agreed in our sprint planning session.

**Comment by RobStallion** [comment]
one possible solution for this could be to do something along the lines of the following...

```
When a user clicks to edit About me form

accessed_at is stored as a variable with DateTime.utc_now

When user clicks save/update accessed_at variable is checked against updated_at in the Postgres table. 

case updated_at < accessed_at do
	true ->
		# no one has edited the data since the user accessed it
		allow user to save changes
	false ->
		# data has been edited since user accessed it so it is out of date.
		# do not allow user to edit it till the new data is loaded.
		# (user will lose what they have entered so far)
		put a flash message telling user that the table has been updated since they loaded it. 
```

**Comment by iteles** [comment]
@RobStallion How much time would this add to the time estimates?

**Comment by RobStallion** [comment]
If it was to be done the way I have mentioned above then I think that would only take an additional 30/60 minutes (including test) as it will not really change the current flow we have in mind, it will just be a check to see if the user is able to save the data or not.

**Comment by iteles** [comment]
For Sprint 3, this was moved to be a lower priority than #86 (which originally built on _this_ issue).
<img width="814" alt="screen shot 2017-09-07 at 12 28 47" src="https://user-images.githubusercontent.com/4185328/30161425-5e4ecb42-93c8-11e7-892b-d25df798c3ae.png">

So for the avoidance of doubt, I am switching the time estimates around on these so this issue now builds on #86.

**Comment by katyedwards** [comment]
? Add allergies prompt to About me Page - @MollieCourtenay

**Comment by iteles** [comment]
@katyedwards Adding 2 hours to this issue to deal with concurrent updating as outlined by @RobStallion above.

**Comment by katyedwards** [comment]
Hi @RobStallion it's looking really good!  One glitch...

When the clinician updates and clicks save on the about me form, it takes them back to their toolkit (the clinicians) and should take them back to the SU's details & meds page.

Also - the updated by ADHD team time/date stamp doesn't seem to work.

Screenshot is clinician view on right (after updating the About me) and SU on left (page has been refreshed but no timestamp).
![screenshot 2018-01-19 09 24 49](https://user-images.githubusercontent.com/24604903/35143921-de608f82-fcfa-11e7-92cb-38c8310e26eb.png)



Tested on evan@email.com and bones@headscape.com

**Comment by RobStallion** [comment]
When testing last updated by locally with the clinician updating a service users 'About Me' it seems to work as expected.

![image](https://user-images.githubusercontent.com/15571853/35146932-92036592-fd04-11e7-9c97-3ad6dce5a30f.png)

Looking into why the same is not happening with the users tested on the staging site

**Comment by RobStallion** [comment]
Found the error. There was no case accounting for the service user making the about me first and then the clinician going to edit it. 

Both the clinician being redirected to caseload and the ADHD team member update now seem to be working as expected.

**Comment by katyedwards** [comment]
Awesome - thanks!  Let me know if you get it deployed and I'll test and close off the issue.

**Comment by katyedwards** [comment]
All good!
