### ISSUE TITLE
Within Admin: assign Teachers to service users (same as clinicians)

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#179]
+ [x] as a super admin, if i have already added a Teacher, I can assign them to a service user.
____
Can split this up to make two issues as this second task can be a lower priority.
+ [x] if a teacher has already been assigned then, when I click to edit the service user, that teacher(s) are already ticked, and I can edit the connections.

Please see #24 and see if this can be fixed for assigning both teachers and clinicians!

**Comment by katbow** [comment]
see comment here for note on this issue https://github.com/healthlocker/oxleas-adhd/issues/163#issuecomment-327494531

**Comment by MollieCourtenay** [comment]
<img width="369" alt="screen shot 2017-09-11 at 15 02 30" src="https://user-images.githubusercontent.com/25012688/30278542-81815dea-9702-11e7-82ea-13158a5e2521.png">

**Comment by iteles** [comment]
Note @katyedwards: This second task is pushing up the time estimate here to a day.

**Comment by katyedwards** [comment]
Working great, but can the UI be updated to match the mock up above - a grey dividing line between clinicians and teachers and increased padding above 'Connect to Teachers'

![screenshot 2018-01-23 16 49 13](https://user-images.githubusercontent.com/24604903/35288703-604d0cea-005d-11e8-9944-64a564834386.png)

**Comment by katyedwards** [comment]
Looks great!
