### ISSUE TITLE
Teacher: Messages - to a SU's Care team 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#183]
As a teacher I can share updates on the Service users progress from my point of view with the Care team.
For epic #188 

+ [x] As a teacher when I click on a service user in my caseload, messages loads, in the room that is created, I can ONLY send messages to the service users care team (NOT Carer or Service user).  
+ [x] Add a line (just like carer's) Send a message to Service User's care team.
+ [x] Teachers' message bubbles will be in teacher colour - #7f88cd
+ [x] remove 'Please note: All service users and family / friends / carers that send messages will see this statement:' from the disclaimer. 
<img width="273" alt="screen shot 2017-09-11 at 15 24 04" src="https://user-images.githubusercontent.com/25012688/30279497-454979e0-9705-11e7-9be1-944803417384.png">

NOTE: Who is in the care team will be listed for the Teacher to read in Details and Meds section 
 (not in caseload or messages page) #205

**Comment by katbow** [comment]
@MollieCourtenay I think I need to know more about the UI for this to estimate better. I'm not sure what the user flow is for teachers, especially when accessing the care team. 

Since a teacher would be able to be connected with multiple users' care teams, the care team link would not work in the same way (this just links to a single care team for service users/carers). Would the care team for each service user be listed how carers are in the clinician caseload?

**Comment by katyedwards** [comment]
I've asked for some more info on what they are expecting here.  Will update as soon as I can

**Comment by katbow** [comment]
thanks @katyedwards. Related is #180. Need to know in general how a teacher views each of these 3 user types (care team, carer, service user), and how they interact with each one.

**Comment by katyedwards** [comment]
Will just be messaging between the teacher and the care team - same as carer's have.

To replace emails which go back and forth at the moment.

**Comment by iteles** [comment]
This comment of @katbow's is relevant here:
https://github.com/healthlocker/oxleas-adhd/issues/180#issuecomment-327503566
<img width="712" alt="screen shot 2017-12-22 at 15 09 40" src="https://user-images.githubusercontent.com/4185328/34302766-3f183636-e72a-11e7-853b-357756cf615c.png">

Upping the estimate to deal with this comment.

**Comment by katyedwards** [comment]
Works Great!
