### ISSUE TITLE
Deploy to Live Environment

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#187]
@RobStallion to add other steps, but just adding the note below so it isn't forgotten!

- [x] Deploy application to server using edeliver 
- [x] Start application using edeliver
- [x] Ensure all environment variables needed for application to run are in the `.profile`
  - [x] generate secret_key_base
- [x] Create database and then tables that will be used in the db
- [x] Set up Super User with same login details as test site

**Comment by reddog** [comment]
@RobStallion Can you please add a time estimate for this issue.

**Comment by reddog** [comment]
@RobStallion Thanks for the time estimate.

The issue, as it currently stands just has a single `set up Super User` task.  Is this going to take 4 hours or are there other steps to complete?  If so, can you please list them?

**Comment by katyedwards** [comment]
@reddog the superuser task was added by me so it wasn't forgotten.  None of the other steps for deployment have been added yet.

**Comment by reddog** [comment]
@RobStallion Following on from @katyedwards' comment, could you add the other tasks for this issue?

**Comment by RobStallion** [comment]
When I started the application I got the following error...

![image](https://user-images.githubusercontent.com/15571853/30169465-6153a634-93e4-11e7-92b3-b5d4ec326511.png)

Believe that this is an error with the database on the server so going to start there.

**Comment by RobStallion** [comment]
Resolved.

![image](https://user-images.githubusercontent.com/15571853/30169614-cff71da0-93e4-11e7-9e7d-3c3ecf0b4d09.png)

The database was not created during deployment. Had to `ssh` into server and run the commands 
```
mix ecto.create
mix ecto.migrate
```

This created the database and the database tables

**Comment by katyedwards** [comment]
Seems ok to me!
