### ISSUE TITLE
Teacher: Details & Meds section

### ISSUE THREAD

**Issue by katbow** [healthlocker/oxleas-adhd#189]
For epic #188 
As a teacher, looking at a service users Details & Meds section, I can see:

+ [x] Teachers can see but NOT EDIT, Medication.
+ [x] Teachers CANNOT see About me.
+ [x] Teachers can see contact info of the SU. (same as Care team view, DOB, email, phone no)

<img width="241" alt="screen shot 2017-09-11 at 15 36 30" src="https://user-images.githubusercontent.com/25012688/30280311-5819ccb2-9707-11e7-8249-20cdba127db7.png">

___________________ 
This section might need to change for teachers, particularly if they are also able to have diary entries. - A: Diary entries will not be in this section. It will be a button added to Tracking Overview for Clinicians and Teachers. 

Will need to know for this section for teacher view:
* What is the section called? - A: Details & Meds.
* What is displayed on this page for contact info? - A: (same as Care team view, DOB, email, phone no)
* Are there any other icons/things teachers will need to access from this section? Similar to how a clinician can access about me/medication from here - A: Teachers can see but NOT EDIT, Medication. Teachers CANNOT see About me.
* As per Healthlocker https://github.com/healthlocker/healthlocker/issues/659 would want to add the care team and teachers to a list underneath the yellow box in Details & Meds section - new issue for that here #205

**Comment by katyedwards** [comment]
@katbow we want to keep it as simple as possible so I would propose it'll be the same as Clinicians, and for both Clinicians and Teachers there would be a 3rd icon for diary where they can both contribute diary entries.

Not sure how the UI for that would work, but that seems like the simplest thing to me.

@MollieCourtenay?

**Comment by katbow** [comment]
Note for this: permissions will need to be updated for who can access to view medication, as right now it is set so that only the user the medication is for can access it.

**Comment by katbow** [comment]
@MollieCourtenay I love the example name in the screenshot

**Comment by katyedwards** [comment]
3/4 done - only remaining point is displaying the care team info.

**Comment by katyedwards** [comment]
Awaiting completion of #279 then will be done.

**Comment by katyedwards** [comment]
Done in #279
