### ISSUE TITLE
Clinician: access Medication notes

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#19]
+ [x] As a Clinician, I access the Medication notes form Details and Meds menu item.

+ [x]  Change title of Details and Contacts menu to Details and Meds
+ [x]  About Me symbol and text appear linking to About Me page
+ [x]  Medication symbol and text appear linking to Medication page

<img width="364" alt="screen shot 2017-07-05 at 15 20 47" src="https://user-images.githubusercontent.com/25012688/27868912-21141976-6196-11e7-9ba3-8589730b8af3.png">

**Comment by MollieCourtenay** [comment]
icon should be in here: #36

**Comment by MollieCourtenay** [comment]
icon for the top of the page ![icons-oxleas_medication big-05](https://user-images.githubusercontent.com/25012688/28971327-749ea7c4-7923-11e7-8a70-70156fbce1a1.png)

**Comment by markwilliamfirth** [comment]
Blocked until integration is complete #90

**Comment by Cleop** [comment]
Do we have the icon for the About Me page? @MollieCourtenay 

For now making the link to the About Me page be a page saying "Coming soon" (with no fancy styling) as @katyedwards informs me that the About Me pages are now out of scope and so not being made yet.

The medication link will take you to the edit page of a patient.

**Comment by katyedwards** [comment]
![icons-oxleas_about me big](https://user-images.githubusercontent.com/24604903/29411287-124869e2-834c-11e7-8a09-5eb30042ed40.png)

@MollieCourtenay can you just have a quick check I've found the right one before @Cleop implements.  Thanks!

**Comment by katyedwards** [comment]
Yes, lovely!
