### ISSUE TITLE
Deployment and SSL documentation

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#191]
As  a future developer on the Healthlocker project
I would like to have full documentation that I can replicate to cover the steps taken to achieve #94 and #125 
So that I can benefit from the knowledge of developers past and not have to research the process again myself.

Currently, pretty much _all_ of this is captured across a number of issues which were followed to achieve #94 and #125, we need to bring this together in our documentation clearly.

**Note:** Scope for this documentation has been requested to be pared down to 'bare bones' documentation as per https://github.com/healthlocker/oxleas-adhd/issues/191#issuecomment-327863277

**Comment by RobStallion** [comment]
What will be needed in this documentation:

- [ ] Instructions on how to deploy a basic phoenix application to Azure ([great readme here](https://github.com/dwyl/learn-phoenix-framework/blob/master/production-deployment.md) which will be linked to in order to avoid duplicating work)
- [ ] Steps 4, 5 & 6 from [this readme](https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md) will need to be recreated for an Azure instance. 
  - have reader update their basic phoenix app to allow static files to be server from `.well-known` file
  - have reader update `.deliver/config` with line to add `.well-known` file to `priv/` during edeliver build process
  - install certbot (linux)
  - start certbot
  - update files when given cert token
  - rebuild, deploy and start app
  - continue certbot and get certificate
- [ ] update nginx config. (will make a default `nginx` config available for reader and will have instructions on what they will have to update themselves)

**Comment by iteles** [comment]
Discussed this with @reddog just after our standup today and the new requirement here is that we strip this documentation down to a more barebones version after much conversation.

The aim is that a developer with an Oxleas-specific repo and a SLaM-provision new Azure environment will have a set of clear steps needed to replicate #168 and #187.

These steps will be a series of step-by-step commands with one sentence to explain what said command does.
It will not include why said action is being performed, why it is useful or provide any further context other than what the command does.

In addition, we will need short and concise documentation (similar to the above) on setting up an SSL certificate https://github.com/healthlocker/oxleas-adhd/issues/94

**Comment by reddog** [comment]
@RobStallion Thanks very much for working on the documentation.

Are there any details on provisioning the database and setting up the initial super user, as per

> Create database and then tables that will be used in the db
> Set up Super User with same login details as test site

in #187?  There's also a reference to:

> generate secret_key_base

Is that covered?

**Comment by RobStallion** [comment]
Do you want instructions for how to add a super_admin in this readme? That is something that is specific to Oxleas only. Healthlocker for example does not even have super_admin as a role so it would not apply to HL.

**Comment by reddog** [comment]
@RobStallion Yes please.  I guess the SLaM HL version of the readme would then be adjusted accordingly.

Outcome needs to be that someone can take this repo plus your document and create a working version of Oxleas that could then be used.

**Comment by RobStallion** [comment]
@reddog adding a super user is probably best done with a function so I am going to have to create a function to add the super user which the reader can then call. This will take some time. I will create an issue for this and add a time estimate to it

**Comment by reddog** [comment]
@RobStallion Can you write the steps you performed for now.  That's a great first version.

**Comment by RobStallion** [comment]
I don't want to add the steps I performed as I had to manually add a password_hash to the database and I don't think putting that on github is very secure

**Comment by reddog** [comment]
@RobStallion Understood, but you could put the steps to alter the database, and the steps to generate the password hash, without listing the password itself.  Would that be insecure?

**Comment by RobStallion** [comment]
@reddog No but it may take as long as creating the function and will be more steps (probably a little more confusing as well) for the reader.

**Comment by reddog** [comment]
@RobStallion I'm not sure I understand why it will take a long time to outline the steps to add the super user.  Could you explain a little further?

**Comment by reddog** [comment]
@RobStallion As discussed, can you please add:

- [ ] details to set up the database and fill with the initial super user, #187 
- [ ] set up Let's Encrypt SSL certificate auto-renewal, #193 

Is there anything else remaining or could this document then be followed to perform a fresh installation?

**Comment by iteles** [comment]
@RobStallion I'm assuming this will require and extra hour or two, but will also remove that time from https://github.com/healthlocker/healthlocker/issues/1063 👍

**Comment by RobStallion** [comment]
@reddog I think that those are all that is missing from the documentation as it stands but I will update the issue if anything else comes to mind. 

@iteles I would estimate another hour for this to be completed.

**Comment by reddog** [comment]
@RobStallion Thanks very much for the update.

Are there any references to provisioning the database?  See https://github.com/healthlocker/oxleas-adhd/issues/187#issuecomment-327825295

Have you had a quick re-read through it to ensure that all other items are included?

**Comment by RobStallion** [comment]
@reddog Thanks for spotting that 👍. I'll add those now.

**Comment by reddog** [comment]
There are no references to the various `config.exs` type files in:

- [ ] `/config/` https://github.com/healthlocker/oxleas-adhd/tree/master/config
- [ ] `/apps/healthlocker/config/` https://github.com/healthlocker/oxleas-adhd/tree/master/apps/healthlocker/config
- [ ] `/apps/oxleas_adhd/config/` https://github.com/healthlocker/oxleas-adhd/tree/master/apps/oxleas_adhd/config

Is there anything in those files that would need customising?

**Comment by RobStallion** [comment]
No nothing in those would need to be updated.

**Comment by reddog** [comment]
I haven't gone fully through the `.exs` config files but there are references to the database and AWS SES, for example.

**Comment by reddog** [comment]
In the `Add environment variables to Azure` section there is the following reference:

> You will need to add the environment variables used to run the application to the `/.profile` file on the server. Some of these will vary from app to app and most are sensitive so you will have to know the variables you need to add.

but there's no list of what those environment variables are (not what values they have, but what they're called).  It would be necessary to search through the source code to find all of the environment variables required.

Can they be listed?

**Comment by RobStallion** [comment]
@reddog I can list them if you like. It should be safe enough to add the list needed without values.

**Comment by reddog** [comment]
@RobStallion I think it's completely safe to list the names of the environment variables.  They can, after all and with a little leg work, be found in the code anyhow.

Are you able to also address the various `.exs` files - database name, AWS SES, anything else?

**Comment by RobStallion** [comment]
The database name that will be used in production can be found in `apps/healthlocker/config/prod.exs` and the AWS SWS variables that are needed are some of the environment variables

**Comment by reddog** [comment]
@RobStallion Thanks - can those details be added to the document?

Should there be a separate mention that an AWS SES account setup is required to be completed in advance?  Any requirements with that setup?

**Comment by RobStallion** [comment]
@reddog I can list those. 

I can mention that an AWS SES account is required (as I say at the top of the doc with the Azure environment and the repo) but I don't think anything about the setup for it should be in this documentation as it is just for SSL and depolyment

**Comment by reddog** [comment]
@RobStallion Thanks for adding in the environment variables.

If there is anything particular about the AWS SES setup to get this app working then it should be listed.

This document is about taking the repo's code (this repo in particular) and a fresh machine and then ending up with a working app.  If there's anything required with third party sites, that should be listed.  Certainly (for now at least), if it's a *standard* third party signup that's required then just listing that should be sufficient.  However, completely missing off that a given third party site account is required will almost certainly lead to future confusion, and a non-working site.

**Comment by reddog** [comment]
@RobStallion Can you please update us on when the following will be added to the documentation:

- [ ] listing environment variables used
- [ ] AWS SES
- [ ] any other third party logins required

**Comment by iteles** [comment]
Closed as per https://github.com/healthlocker/oxleas-adhd/pull/210#issuecomment-329429701 👍 
<img width="657" alt="screen shot 2017-09-14 at 16 19 00" src="https://user-images.githubusercontent.com/4185328/30438168-78da19bc-9968-11e7-9740-1cecd5113947.png">
