### ISSUE TITLE
Review of copy update PRs

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#192]
There are currently 11 open copy PRs in this repository which will need to be reviewed. Given the time sensitivities of our current sprint, we are capturing this as an issue so that the time can be accounted for.

2 of them are also failing CI and may need some additional TLC.

<img width="349" alt="screen shot 2017-09-06 at 17 17 50" src="https://user-images.githubusercontent.com/4185328/30123478-01d1ac52-932a-11e7-8157-22a211acb9bb.png">

**Comment by reddog** [comment]
PR #170 looks fine in terms of changes in the included commit.  Travis CI build failed due to database access error.  I've added a comment to the PR - is this a sign of a potentially wider (database connectivity) issue or just something that can be re-tested?  See https://github.com/healthlocker/oxleas-adhd/pull/170#issuecomment-327727203

**Comment by RobStallion** [comment]
@reddog I have re-run the Travis CI build and it passed this time round without any changes having to be made. As all the tests prior to, following and on the rebuild of this passed I do not think that it is something that we need to worry about. It was probably a connection issue at the one moment in time that caused Travis to fail.

**Comment by iteles** [comment]
Between @RobStallion 's review of #170 today and @SimonLab's review of the majority of the PRs tonight, we should be down to 1 hour time estimate on this to:
+ [ ] Review and help fix #177 
+ [ ] Deploy this + #4 to TEST
+ [ ] Quick check of this on the TEST server

**Comment by iteles** [comment]
All copy PRs have now been merged in and deployed to TEST. The remaining part of this issue is captured in #141 which is lower priority, so closing this issue in favour of that one.
