### ISSUE TITLE
Admin 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#2]
#1  #34  #6  #21 #22  #23  #24 #25 #30 #38

**Comment by RobStallion** [comment]
What permissions would this user need? There is a role admin in healthlocker which allows editing of posts. Would it be the same deal here?

**Comment by MollieCourtenay** [comment]
By Admin, I mean the part of the service where the Super Admin manages accounts.

**Comment by iteles** [comment]
All issues here apart from https://github.com/healthlocker/oxleas-adhd/issues/25 and https://github.com/healthlocker/oxleas-adhd/issues/38 included in sprint 1
