### ISSUE TITLE
Content training 

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#20]
Would you be interested in some training from @katbow on how to make content changes yourselves, as discussed previously with @MollieCourtenay?

This would enable you to create your own branches where you can update content and submit pull requests for us to review. 

This would be time/money saving for this project and would allow you to make these changes as and when you need to, should content change.

**Comment by MollieCourtenay** [comment]
Yes please!!  @RobStallion @katbow 

If we are sticking with running this project 17th - 31st July.
Then,  24th/25th would be good for me :)

**Comment by MollieCourtenay** [comment]
@katbow actually - when are you away?

**Comment by katbow** [comment]
10th-25th Jul, then in Portugal from 27th. So if in person would work best for you, then I guess that would only leave the 26th 😕 . Alternatively, I can put together a guide and we can work through it remotely together.

**Comment by MollieCourtenay** [comment]
Hey @katbow  
If you are happy to do it on 26th? That would be truly wonderful.
Me and Katy will learn from you.
Just waiting to hear if our place will be busy or empty - being a wednesday.
Can we do it at the beginning of the day, leaving us the rest of the day clear to upload the content? :geek:

**Comment by katbow** [comment]
Absolutely, we can do it first thing! Just let me know where is best 🙂

**Comment by katbow** [comment]
We confirmed that we will be able to add the `web/templates` folder to the repo. 

Also, I completed most of those other sections/notes during the plane journey yesterday. I'm going to finish up the last bits this morning and push it up for you 🙂

**Comment by katyedwards** [comment]
Lovely thanks!  Do you reckon the templates will be added today for us to start work? @katbow

**Comment by katbow** [comment]
Yup, it should be.

Also just thought it would be good to add the things I'm working on now to this issue.
For HTML basics:
- [ ] Headers from H1 - H4
- [ ] Phoenix links, including examples for internal, external, mailto: and tel: links
- [ ] Lists
- [ ] Basic styling
    - [ ] strong and i
    - [ ] classes (b, i, tc)
- [ ] Images
- [ ] Special characters (eg. &amp)

Adding to/clarifying instructions in `content-tutorial.md`
- [ ] How to find and edit after searching (need to use file path)
- [ ] Continuing making changes after creating an in-progress pull request
- [ ] Note to stay inside bottom `</div>` when adding new `<p>` tags

**Comment by katyedwards** [comment]
Hi @RobStallion @katbow any news on when the templates folder will be ready for us to start updating the content?

**Comment by katbow** [comment]
yep, it's merged in now so it's all ready now!
