### ISSUE TITLE
Edit posts rights for Super Admins

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#212]
+ [x] As a super admin, I have the permissions to Edit posts.

______________________
This is something we noticed on the weekend and not sure why this is not available? Whereas it is in Healthlocker.

Oxleas - the Edit link is missing.
<img width="757" alt="screen shot 2017-09-11 at 10 29 28" src="https://user-images.githubusercontent.com/25012688/30267968-1bbd5836-96dc-11e7-833c-0d986ab3040d.png">
admin user gets a message when I tried to access the url posts/XX/edit
<img width="777" alt="screen shot 2017-09-11 at 10 29 22" src="https://user-images.githubusercontent.com/25012688/30267969-1c07f13e-96dc-11e7-93e4-db5512853d0a.png">

Healthlocker:
<img width="343" alt="screen shot 2017-09-11 at 10 30 55" src="https://user-images.githubusercontent.com/25012688/30268039-4d34b0f8-96dc-11e7-9d00-94a19a9011a8.png">

**Comment by iteles** [comment]
@RobStallion Could you please take a quick look and diagnose this?

**Comment by MollieCourtenay** [comment]
this works thanks!
