### ISSUE TITLE
Staff (clinician) caseload: Displaying teachers

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#214]
NEEDS ESTIMATING. This may have been done within #180 ??
____
## Acceptance Criteria
+ [x]  as a Clinician, I see teachers listed on my caseload underneath a service user and carer. 
+ [x] the teachers **First name Last name** _(Role, organisation)_
+ [x] as a clinician, I may see the same teacher listed multiple times if they are associated with multiple service users.
+ [x] the outline for teachers is lilac - like the lilac in the halo logo.
<img width="514" alt="screen shot 2017-09-11 at 17 04 44" src="https://user-images.githubusercontent.com/25012688/30284619-5627e81a-9713-11e7-9d2c-5ad9bfd4aca7.png">

**Comment by iteles** [comment]
@MollieCourtenay This has been correctly split out from #180 👍 Thanks!

**Comment by katyedwards** [comment]
Border Colour for Teachers is #7f88cd please

**Comment by katyedwards** [comment]
Almost there...

- [ ]  the teachers First name Last name (Role, organisation)
Currently doesn't display organisation.

**Comment by SimonLab** [comment]
@katyedwards just to comfirm do you want to display the role and the organisation for each teacher or just the string "(Role, Organisation)"?

**Comment by katyedwards** [comment]
Sorry - I missed the notification for this.

So it should list the details recorded in the admin portal so it would list something like

Katy Edwards (_Project Manager, Mindwave Ventures_)

**Comment by katyedwards** [comment]
Perfect thanks!
