### ISSUE TITLE
Teachers - Structured Form

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#221]
### Feature Aim:

A structured form where teachers can enter info which is shared.

- It's  more about structured information than messaging or diary entries. 
- It mimics a paper questionnaire they currently use
- The end game involves interoperability with Rio. A structured teachers report form on headscape allows us to easily port that information to the right place in Rio in due course.

## Acceptance Criteria:
**Teachers**
- [x] Teacher can access for via an icon on the details and meds tab
- [x] Teacher can fill in form on one long page of questions
- [x] Teacher can return to the form at any time and edit any/all of the questions - i.e. drop downs and free text boxes remain editable
- [x] No character limit so teachers have the option to keep adding without overwriting previous entries
- [x] All fields are optional so if teachers want to leave stuff blank and still save, they can.

**Care Team**
- [x] Care team can access the page via an icon on the details and meds tab
- [x] Care team can view ONLY (not edit) form
- [ ] Care team see a timestamp showing when the form was last updated and who it was updated by

**Service User**
- [x] SU can access the form via an icon on their toolkit page (at the bottom)
- [x] SU can view ONLY (not edit) form (will appear as another icon on goals & tracking page)
- [ ] SU see a timestamp showing when the form was last updated and who it was updated by

**Carer**
-  FYI, Carers cannot see or edit the form at all

NOTE:
For now the feature will be called 'School Feedback' but the client team want to give teacher the opportunity to input on the name so they feel ownership so this may change.

**Old Notes to explain some of the comments below!**
They are also interested in the ability to 'archive' previous inputs so it isn't just edited and overwritten like Meds/ about me.

Can you give any kind of time estimate range on adding some way of archiving - based on the fact that there is no guidance on how this should work yet?!

Off the top of my head I would suggest:

- Forms submit like a diary entry and appear (uneditable) at the bottom of the page.  
- Last 3 display then click on 'see more' to load more to avoid the page becoming too slow.

Is that enough info for a rough estimate/ recommendation of a much better idea?!

**Comment by iteles** [comment]
@katyedwards When you say 'view & edit form', is it safe to assume that you're discussing the editing of the _content_ of the form, rather than the form itself (i.e. which fields a form displays)?

**Comment by katyedwards** [comment]
@iteles yes just the content

**Comment by katbow** [comment]
@katyedwards what is Rio? Is there any information I need to know about it in order to know how exactly this form is structured? Is it like a report card? I tried to look it up but I just get things about teachers in Rio de Janeiro hah. 

For the archiving functionality, I am guessing there would still need to be editing/some way to build on top of another submitted form? My initial thought is to save as a new entry each time, which would show changes over time. However, this may mean reentry of data as the form wouldn't load data from previously entered forms (as this would be an edit and overwrite the last information).

**Comment by katyedwards** [comment]
@katbow Rio is the trust's version of ePJS.  Don't worry about how it should be structured - the two systems communicating is a long way in the future.  It'll be a fairly simple form and Oxleas will have to give us the correct names of the boxes if they want to transfer data in the long run.

For archiving - would it be a big job to allow an edit button on the one most recent entry or click to add a new?  Then they'd have both options?

**Comment by katbow** [comment]
They could have both yes, but with an edit it overwrites the previous data. So we will need to archive the information in a different way with edits.

**Comment by katyedwards** [comment]
@katbow as with #220 we just need a high level estimate at this stage.

We're assuming that it'll be c 4 days to do a new form as that was the estimate for About me.

Do you think the archiving will probably double that?  Or do you think it's likely to be more/less?

This is just so they can think about what they want to include in the next phase.

**Comment by katbow** [comment]
Create form (new) T2h
Save form (create) T2h
Edit form (edit) T2h
Save edited form (update) T2h
Styling throughout -T4h

Archiving I would put as 1-2 days extra on top of it.  

So total without archiving is 1.5 days & with archiving is 3.5 days (all paired estimates!)

**Comment by katyedwards** [comment]
Just to confirm at this stage we are proceeding with the option **without** archiving

**Comment by katyedwards** [comment]
Icon here: 
![toolkit_teacherform](https://user-images.githubusercontent.com/24604903/34988770-cee76098-fab7-11e7-8377-450d380a18b3.png)

Let me know if you have any problems with it.

**Comment by katyedwards** [comment]
Note to self - timestamp

**Comment by katyedwards** [comment]
[Teachers Questionnaire Jan 18.docx](https://github.com/healthlocker/oxleas-adhd/files/1651247/Teachers.Questionnaire.Jan.18.docx)

Name to be "School Feedback" for now (they are going to speak to teachers about the name, so hopefully this will be easy to change later if needed?)

**Comment by katyedwards** [comment]
@RobStallion I have updated the initial post above - hopefully it now covers anything, but shout if anything isn't clear!

**Comment by RobStallion** [comment]
@katyedwards One idea for archiving

Teacher goes to caseload and clicks the link to 'School feedback'

Assuming they have made a feedback form in the past, they are taken to a page that displays the data on screen and have the choice to either update it or archive it.

If they click archive then we update a field in the database so it is listed as archived. Then the user would be redirected to create a new form. 

Estimate for this would be between 1.5 & 2 days extra (based on the features I have listed here)

### Tech bit

Have `new` and `create` routes for initial creation
Have `edit` and `update` routes for updating existing forms
Have a `show` route that will just display the info of the most recent feedback form and will have a list with links to older archives. It will redirect to `edit` or `new` as needed.

In terms of database set up, a user (service_user) would have many feedback forms associated to them (created by a teacher)

When a teacher clicks to archive we update a field in the database called `archived` to true (will be set to false by default)
If all `feedback_forms.archived == true` then a user would be directed to the new route by default.

**Comment by katyedwards** [comment]
@RobStallion Thanks for doing the thinking around this.  For this phase I think stick with the basic version where the form is just editable (like meds & about me) but shows a timestamp.
e.g.
Teacher clicks on School Feedback Icon
First time they do it they get a page of empty text boxes and unselected dropdowns
All future times they see the page as it was left on their last visit with filled in boxes and selected dropdowns and they can edit, add, delete, re-select to their heart's content. 

The client decided to de-scope the archiving when we planned out and costed the work, so we haven't talked about the 'design' of it with them in enough detail to proceed.  If you can code leaving yourself options though then great.

**Comment by RobStallion** [comment]
@katyedwards. What do you want a service user to see if a teacher has not yet created a form for them?

**Comment by katyedwards** [comment]
Can we display a message saying "There is no school feedback view yet"

Thanks!

**Comment by katyedwards** [comment]
Not quite complete @RobStallion 

- [ ] Clinician can currently edit the structured form (shouldn't be able to)
- [ ] No time stamp showing who updated it (clinician view)
- [ ] No time stamp showing who updated it (SU view)

**Comment by RobStallion** [comment]
@katyedwards Clinicians being able to edit the structured form was moved into issue #280 and is currently awaiting review. 

Good spot on the time stamp. I must have removed it in error when I refactored the code. Will put that back it

**Comment by katyedwards** [comment]
Looks good now, thank you!
