### ISSUE TITLE
Change Error Pages

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#224]
Oxleas Pen Testing highlighted that the error pages give away too much info.

Implement same fix/ change as for HL:
https://github.com/healthlocker/healthlocker/issues/1064

**Comment by katbow** [comment]
@katyedwards this is done now and I will redeploy after I finish deploying HL staging. I'll deploy to test first, and after you sign off I'll deploy to live.

**Comment by katyedwards** [comment]
Fab, cheers me dear!

**Comment by katbow** [comment]
Deployed now! Here's an easy url to test for a non existent story

https://test-focus.headscapegreenwich.co.uk/posts/-1

**Comment by katyedwards** [comment]
Looking good!  Ready to deploy to live!

**Comment by katbow** [comment]
Deployed to live now too and works in the same way https://focus.headscapegreenwich.co.uk/posts/-1
