### ISSUE TITLE
Clinician Dashboard - see alert/ notification for new messages

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#228]
On the Clinician Dashboard view, if I receive a new message from a service user, carer or teacher, I will see a red dot on their entry 

Something much much much prettier than this:
![screenshot 2017-10-20 14 44 06](https://user-images.githubusercontent.com/24604903/31823878-700f742c-b5a5-11e7-9ff1-209d82c7c87e.png)

- As soon as the message has been viewed by anyone on the care team, the alert/ notification will be removed for all team members.

- Applies to messages only - no other kind of info being updated.

- Applies to the clinician view only, no one else gets alerts at the moment.

**Comment by katbow** [comment]
I need to do a brief look about for this before estimating. Wanted to let you know so you know the estimate is in progress!

**Comment by katbow** [comment]
General overview:

Need to include if a room `has_unread` messages as part of a table (probably `rooms`). This can either be a boolean (true/false) value for now. I think it will be that when a new message is added by any of service user, carer or teacher, then `has_unread` will update to `true`. When a clinician joins a room, then `has_unread` will go back to `false`. 

For each room in the clinician display, then we can do something like `if room.has_unread -> display unread notification dot`

That's a *highly* simplified view of what will need to be done. Updating the channels for rooms/messages will likely be the longest part as we may need to add new messages to handle,

* Update schemas to include if messages are read - **T4h** Making the model & migration itself is reasonably fast, but the t4h includes 'decision time' for working out the best structure for the schema.
* Update channels to add if `has_unread` is true or false - **T1d**  This will includes creating new_messages to handle & testing both the changes to the room channel. 
* Create database helper functions to update tables for channel events - **T1d** Includes time for updating tables on incoming (non-clinician) messages, and for reversing to false when clinicians visit the room, and testing the new database functions
* Styling of related section - **T4h**

**Comment by katbow** [comment]
Also P.S. for myself, [this repo](https://github.com/smpallen99/ucx_chat) seems very useful!

Some relevant code:
* https://github.com/smpallen99/ucx_chat/blob/cc910e0c2a784cdd0e4004f75084ffd0a881a648/web/views/side_nav_view.ex

* https://github.com/smpallen99/ucx_chat/blob/cc910e0c2a784cdd0e4004f75084ffd0a881a648/web/channels/router.ex

* https://github.com/smpallen99/ucx_chat/blob/cc910e0c2a784cdd0e4004f75084ffd0a881a648/web/services/channel_service.ex
* https://github.com/smpallen99/ucx_chat/blob/cc910e0c2a784cdd0e4004f75084ffd0a881a648/web/channels/user_channel.ex
* https://github.com/smpallen99/ucx_chat/blob/cc910e0c2a784cdd0e4004f75084ffd0a881a648/web/static/js/room_manager.js

**Comment by katyedwards** [comment]
Lovely job thanks!
