### ISSUE TITLE
Within Admin system: edit a SUs clinician connections

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#24]
+ [x] As a super admin, from the landing page, I can click on an individual service user to edit the clinician connections of that individual service user.

+ [x] If I click to edit, the service users account details are displayed. I can select or deselect clinicians, then click save.  I cannot edit other account details.

<img width="821" alt="edit su" src="https://user-images.githubusercontent.com/25012688/28059998-d2dc3b1c-661d-11e7-86e9-55b0a1c07692.png">

**Comment by iteles** [comment]
Editing details of clinicians and carers as well as carer connections to SUs are not included in the backlog at this stage, approved by @katyedwards at our sprint planning session.

**Comment by RobStallion** [comment]
Rest will be done when connecting umbrella

- [ ] As a super admin, from the landing page, I can click on an individual service user to edit the clinician connections of that individual service user.

**Comment by katyedwards** [comment]
@MollieCourtenay I raised another issue #124 in the backlog, but just noticed it is in the AC that you can select or deselect.

Right now, when you click on an SU to view the details, all the staff become unticked so you can't see who was assigned previously.

Will leave you to decide whether to accept, close and leave the other issue in the backlog, or whether to leave this open to be changed.

**Comment by MollieCourtenay** [comment]
@katbow @RobStallion is that the expected behaviour? ^^
It is not what I would have imagined? 

Personally I don't think this is a new issue, but a fix of the existing one.

**Comment by katbow** [comment]
I thought the ticked checkboxes for the edit wireframe were in the 'end' state, like how they are in adding a service user wireframe. 

For best UX, I guess it depends on how the super admins are told about changes. If they are just given the full list, then having them default to unchecked would prevent errors, such as leaving clinicians in that shouldn't be part of the care team. If they only know to add StaffMemberA in addition to what's already there, or remove a single staff member & keep the rest, then having them preselected makes more sense.

**Comment by MollieCourtenay** [comment]
@katbow apologies if the design hack was misleading, due to the smallness of this project I put more efforts into making the ACs clear and writing the content out in each issue than with making full sets of mock ups.

In order to deselect (as written in the AC), you'd need to have an already ticked box.

This would be better UX - as it does not rely on the admin remembering what the set up was what previously. 

You're closer with what say in your second part of your comment, they will 90+% of the time only be making small additions or subtractions to clinician connections, e.g. if a new staff member joins the team.

**Comment by MollieCourtenay** [comment]
@Cleop @katbow this is the one for keeping staff ticked

**Comment by katyedwards** [comment]
Works beautifully now, thank you!
