### ISSUE TITLE
Display Consent from Account in Clin Details & Meds

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#246]
Display the SU consent choices on the Clinician view 'Details & Meds' tab

Details to follow

**Comment by iteles** [comment]
@katyedwards We're not sure what the SU consent choices are!

**Comment by katyedwards** [comment]
Sorry!

So there's a couple of things...
In #245 we need to add text so that the users' consent tickbox on the consent tab in account is to agree to the terms of service and privacy statement as well as sharing their data for research because they don't go through the sign up process and consent as HL users do.

Right now the team are having to onboard people in clinic so they can sign a paper consent form.
They want to be able to see that people have ticked the box in the clinician dashboard

It'll display on the Details & Med tab under the yellow details box

I'll try to mock something up but my laptop is playing up!

**Comment by katyedwards** [comment]
This has been totally de-scoped - for now (on advice from IG) they will go with verbal consent needed only and it won't be stored/ recorded on the platform.
