### ISSUE TITLE
GoogleAnalytics

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#273]
Can we hook in Google Analytics??

Time estimate please

**Comment by katyedwards** [comment]
Google analytics <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113820085-1"></script>

**Comment by RobStallion** [comment]
@katyedwards This doesn't look quite right. Could you tell us where you got this from as it might help us shed some light on it. Thanks 👍

**Comment by reddog** [comment]
The `script` link provided is the first line of the required tracking snippet, see https://developers.google.com/analytics/devguides/collection/gtagjs/

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'GA_TRACKING_ID');
</script>
```

Will the `GA_TRACKING_ID` be set from an environment variable?

**Comment by katyedwards** [comment]
Thanks @reddog have sent that link over to James to provide the full data

**Comment by katyedwards** [comment]
Full info:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-113820085-1"></script>
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'UA-113820085-1');
</script>
```

**Comment by katyedwards** [comment]
Hopefully that looks better!

**Comment by katyedwards** [comment]
Just to check @RobStallion for Oxleas to test, should they just see data start to appear in googleanalytics already?

**Comment by RobStallion** [comment]
@katyedwards the code above has been merged in and deployed to staging.

**Comment by katyedwards** [comment]
Client has confirmed they are receiving data!
