### ISSUE TITLE
Issues with permissions of teachers

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#279]
You are able to edit medication as a teacher which should not be the case. Steps to replicate

 - Log in as a teacher
 - go to caseload
 - click on a service user you are connected with
 - click on medication

Permissions of the these users need to be updated so that they are only able to access pages that they are intended to.

**Comment by katyedwards** [comment]
Teachers can also currenly edit About me - they shouldn't be able to see it at all
(may already be fixed by this, but raising it here in case @RobStallion

**Comment by katyedwards** [comment]
Teachers can still view and edit the About Me Page.   Is this waiting to be deployed @RobStallion ?

**Comment by katyedwards** [comment]
- [ ] Teachers can still see and edit About Me - they shouldn't be able to see it or edit it.

- [ ] Teachers cannot see Meds - they should be able to View it, but not edit (if you click on the meds icon you just see the FAQs, but no completed meds info, even if it exists for that user).

**Comment by katyedwards** [comment]
Looks good now, thanks!
