### ISSUE TITLE
Oxleas live site is down

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#287]
![screenshot 2018-01-31 13 04 56](https://user-images.githubusercontent.com/24604903/35624600-5bf8b164-0687-11e8-85d0-f25db6d62ef4.png)

Can someone have a look into this ASAP - the Oxleas team spotted it so were presumably trying to use it!

**Comment by RobStallion** [comment]
@katyedwards Could you please ask SLaM to check if they had restarted the azure servers at any point or if they have any logs that might let us know what happened?

**Comment by katyedwards** [comment]
@RobStallion The VM became unresponsive at 5.29pm so the azure server restarted itself automatically 4-5 mins later.

![image001](https://user-images.githubusercontent.com/24604903/35635595-a4a6ee3e-06a6-11e8-963f-c93e0985cead.png)


Matt has checked the logs and there is nothing in the activity logs so his team hadn't touched it.

![image002 1](https://user-images.githubusercontent.com/24604903/35635605-ab287e9e-06a6-11e8-87cc-4b099d09dc11.png)

**Comment by katyedwards** [comment]
@reddog I didn't get any kind of server monitoring alert when it went down - the first I knew was when Oxleas told me.  Should I have got an email when the thing went down?

**Comment by RobStallion** [comment]
@katyedwards Thanks a lot for getting that. It's really good to know. Do you know if this effected the `oxleasadmin@Oxleas-HL-Test` server as well?

**Comment by katyedwards** [comment]
I'll ask Matt.  If it happened on the test site too then your script worked a charm!

**Comment by RobStallion** [comment]
@katyedwards Did you ever hear back from Matt on this?

**Comment by katyedwards** [comment]
No - or not yet at least.  Can you still do your bit to test at least? @RobStallion

**Comment by katyedwards** [comment]
I'll move it down the priority list.

**Comment by katyedwards** [comment]
Closing this and moving the issue into the HL Tech Support Sprint
