### ISSUE TITLE
Add script to restart Oxleas app if production server ever reboots

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#289]
Relates to [HL #1148](https://github.com/healthlocker/healthlocker/issues/1148).

**Comment by RobStallion** [comment]
Script has been written on the prod server but have not been able to test that it is working yet as we would need to temporarily take the production site down. 

@katyedwards is checking with Oxleas when the best time for us to test this would be.

**Comment by katyedwards** [comment]
@RobStallion Tuesday 6th during the day would be good please - the clinical team are off.

**Comment by katyedwards** [comment]
No news from Matt on whether/ when he can restart the server, but can you still do your bit to test at least? @RobStallion

**Comment by RobStallion** [comment]
Yeah that is not a problem @katyedwards. I will give it a go in the next 30 minutes or so and will update the issue accordingly.

**Comment by RobStallion** [comment]
Taking the oxleas live site down

**Comment by RobStallion** [comment]
Started the oxleas live site using the `service` file. Seems to be working as expected.

**Comment by RobStallion** [comment]
Site appears to be running as expected. Going to stop the app running now and run the following...
```
systemctl enable app_name.service
```

This should allow the application to be started when the server boots up.

**Comment by RobStallion** [comment]
```Created symlink from /etc/systemd/system/multi-user.target.wants/oxleas.service to /lib/systemd/system/oxleas.service.```

Everything appears to be working as expected.

@katyedwards All that is left is for SLaM to reboot the server at some point to test this.

**Comment by reddog** [comment]
@RobStallion Just to check, where you've put `/lib/systemd/system/oxleas.service` did you mean `/etc/systemd/system/oxleas.service` ?

Were you waiting for Matt to be available in case anything unexpected went wrong or something else?  You should be able to restart the server with `sudo reboot`

**Comment by RobStallion** [comment]
@reddog `/lib/systemd/system/oxleas.service` is the correct file path. 

If SLaM are happy for me to reboot the server the way you suggested then I would be happy to give it a go 👍

**Comment by katyedwards** [comment]
@RobStallion either way leave it til Weds and the support day then we can hopefully find out from SLaM what is happening!

**Comment by ghost** [comment]
Waiting for confirmation from SLaM that they are happy for us to proceed with restarting the server.

**Comment by ghost** [comment]
Tested I believe
