### ISSUE TITLE
Internal Server Error on Clinician Caseload

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#298]
On Test Site:

If I login as a clinician, I am directed to my caseload and get an internal server error.

If I go to any other pages (while logged in as clinician) they load fine and I can access them, but if I try to return to my caseload I get an internal server error again.

Do you need any more info than that?

**Comment by RobStallion** [comment]
@katyedwards could you please provide the details for the user/users that you logged in with. 

I have logged in with `doctortest@headscape.co.uk` and I am able to view the caseload

![image](https://user-images.githubusercontent.com/15571853/35980294-412acc30-0ce2-11e8-8433-e7758d9a7c8f.png)

**Comment by katyedwards** [comment]
Sorry, issue was on the test site after the deployment yesterday - it may be working now though with the fix you've done so I'll check again.

**Comment by katyedwards** [comment]
Just checked - issue still exists.

I have tried logging in with bones@headscape.com and bev@headscape.com (both p/w: password)

Still getting internal server error on caseload, but rest of site ok.

**Comment by RobStallion** [comment]
@katyedwards I cannot log it with the details above. Can you double check the details for me please

**Comment by katyedwards** [comment]
@RobStallion are you on the test site?  I can login fine with both on my end.

**Comment by RobStallion** [comment]
I might be very dense sorry @katyedwards. I am on 
```
https://focus.headscapegreenwich.co.uk/login
```
Using the email `bones@headscape.com` and the password `password`

**Comment by katyedwards** [comment]
A wee bit dense ;oD

Try: https://test-focus.headscapegreenwich.co.uk/

**Comment by RobStallion** [comment]
Oh gosh 🙈

**Comment by RobStallion** [comment]
@katyedwards that should be sorted now. Please log in with as many clinicians as possible 👍

**Comment by katyedwards** [comment]
Yep working now thanks!

**Comment by katyedwards** [comment]
Sorry @RobStallion I think you've fixed it on the SU toolkit, but now I'm getting internal server error when I login as a clinician again!!

**Comment by katyedwards** [comment]
And teachers!  I can view the caseload, but I get an internal server error as soon as I click on any of the users listed.

**Comment by katyedwards** [comment]
I'm back in!  Thank you!
