### ISSUE TITLE
Service user: input About me form

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#30]
+ [x] As a SU, I can write into / edit a my About me form.
+ [x] As a SU, I can see who from my care team made the last updates and when.
+ [x] As a SU, I can see when I last updated my About me form.
+ [x] As a SU, I can save my edits.
+ [x] use normal Healthlocker dark blue, not this other blue.

<img width="356" alt="screen shot 2017-07-11 at 10 47 57" src="https://user-images.githubusercontent.com/25012688/28062617-6d82a1b2-6626-11e7-8502-d2e0368dee84.png">

**Comment by iteles** [comment]
Building on #17, this will require an additional 1 hour

**Comment by iteles** [comment]
For Sprint 3, this was moved to be a higher priority than #17 (which this issue originally built on)
<img width="814" alt="screen shot 2017-09-07 at 12 28 47" src="https://user-images.githubusercontent.com/4185328/30161385-241b213c-93c8-11e7-8c96-2a7c183c6975.png">

So for the avoidance of doubt, I am switching the time estimates around on these so that #17 now builds on _this_ issue.

**Comment by katyedwards** [comment]
? Add allergies prompt to About me Page - @MollieCourtenay

**Comment by Cleop** [comment]
Mobile designs: see medication page for mobile design example and copy this as a guide.

**Comment by RobStallion** [comment]
Was getting the following error when trying running the command `mix deps.get`

```
[error] GenServer Hex.Registry.Server terminating
** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
    (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :socket_closed_remotely})
    (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
    (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:get_package, "hexpm", "phoenix_live_reload", {:error, :socket_closed_remotely}}
```

Was able to resolve this by changing wifi networks. Not exactly sure what the problem was

**Comment by RobStallion** [comment]
Currently trying to generate a migration file with the command `mix_ecto.gen.migration create_about_me` but when I do I am getting the following error...
```
== Compilation error in file lib/healthlocker/endpoint.ex ==
** (CompileError) lib/healthlocker/endpoint.ex:45: module Appsignal.Phoenix is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/healthlocker/endpoint.ex:45: Healthlocker.Endpoint (module)
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Currently looking into error.

**Comment by RobStallion** [comment]
Have not been able to get this command to work despite the error giving me a good starting place to look. Did not want to spend too much time trying to debug it so I have manually added the migration file and it has created the table in the DB as expected.

**Comment by katyedwards** [comment]
Looks great, all seems to be working now, thanks!
