### ISSUE TITLE
Sleep data is only displaying data for one day in the week

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#315]
![image](https://user-images.githubusercontent.com/15571853/36261915-d6d8cee6-125d-11e8-9a15-f5a3ff0a9777.png)

**Comment by katyedwards** [comment]
Sorry I might have missed this on the call - is this a new bug?  I moved it down as I assumed it was to do with the seeds issues on the other bugs, but maybe not?!  @RobStallion

**Comment by ghost** [comment]
? is this only occurring with the seeds dummy@data user?

Seems to be ok on my account (have only tested 2 consecutive days, not a whole week yet).

**Comment by RobStallion** [comment]
Thanks @katyedwards Well spotted 👍. This was an issue with the dummy data, not the application itself. Relates to [this pr](https://github.com/healthlocker/oxleas-adhd/pull/312). Will add all further updates there.
