### ISSUE TITLE
Remove superfluous sections from clinician view of teacher

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#316]
**As a clinician, when I click on a teacher in my caseload**, I see 2 tabs:
- messages
- details & meds (with the school feedback form and the teachers personal details 

Teacher's personal details:
Teacher's name, role, school and email address - same style as the SU personal details box but with a purple background.

**As a clinician, when I click on a service user in my caseload** and look at the details and meds tab, I see about me, meds and SU personal details, but NOT school feedback.

@RobStallion this is slightly more changes than when we discussed on the call, but will make more sense to users separating out SU data and Teacher data about the SU.

**Comment by ghost** [comment]
@RobStallion it's looking good!
