### ISSUE TITLE
Edit email for feedback email

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#33]
Send to:
+ [x] Mollie mindwave email
+ [x]  oxl-tr.focusadhd@nhs.net

**Comment by katyedwards** [comment]
Oxleas email: oxl-tr.focusadhd@nhs.net

**Comment by markwilliamfirth** [comment]
Blocked by #50

**Comment by markwilliamfirth** [comment]
@katbow is this a quick one @Cleop could do?

**Comment by katyedwards** [comment]
@RobStallion assigning to you while you wait for subdomain for SSL

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/29714836-be24bb48-899c-11e7-92a1-9a07ae598afd.png)

While running manually.

@MollieCourtenay can you check if you received my feedback email? Double check your spam if it's not in the inbox because my forgotten password emails were all in spam

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/29715056-8f3db9e6-899d-11e7-9759-433ca4d153f7.png)

Sent from deployed site

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/29715286-94e79dd4-899e-11e7-86d2-0bc4e129bc06.png)

@MollieCourtenay could you also check to see if you received the this email please? If you did then this issue can be closed.

**Comment by MollieCourtenay** [comment]
Ive got two emails  - they were in spam.

@RobStallion

**Comment by RobStallion** [comment]
@MollieCourtenay did you get the one with the subject line saying testing with 2 emails?

**Comment by MollieCourtenay** [comment]
<img width="832" alt="screen shot 2017-08-25 at 14 20 07" src="https://user-images.githubusercontent.com/25012688/29715747-85ce7b04-89a0-11e7-9166-7aa03d9ce0c7.png">
<img width="817" alt="screen shot 2017-08-25 at 14 20 03" src="https://user-images.githubusercontent.com/25012688/29715748-85d44296-89a0-11e7-8b05-ddde0a50c373.png">

**Comment by MollieCourtenay** [comment]
@RobStallion  Only these ones ^^

**Comment by RobStallion** [comment]
Ok. Thanks
