### ISSUE TITLE
SU: access medication notes - More Padding

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#36]
+ [x] as a service user, I can access the Medication notes feature, via a new icon and button at the bottom of the Home page (Renamed from goals and strategies)

![oxleas-mockup](https://user-images.githubusercontent.com/25012688/28014778-d2b8d978-6565-11e7-90a3-b53eeb0c3b8d.jpg)

Mollie - need to supply an icon.

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please supply the icon for medication notes

**Comment by MollieCourtenay** [comment]
icon for the top of the page ![icons-oxleas_medication big-05](https://user-images.githubusercontent.com/25012688/28971327-749ea7c4-7923-11e7-8a70-70156fbce1a1.png)

**Comment by markwilliamfirth** [comment]
Blocked until #90 is complete

**Comment by Cleop** [comment]
@MollieCourtenay - do we have the 'About Me' icon?

For now making the link to the About Me page be a page saying "Coming soon" (with no fancy styling) as @katyedwards informs me that the About Me pages are now out of scope and so not being made yet.

The medication page will take a user to a non-editable view of their medications (if these have been set). If these have not been set then this will take you to the medication faqs page,

**Comment by MollieCourtenay** [comment]
+ [ ] add some padding above the new medication icon. So it is not so close to the diary button.
<img width="301" alt="screen shot 2017-08-22 at 17 12 35" src="https://user-images.githubusercontent.com/25012688/29575690-3350d9f2-875d-11e7-814d-a4239646d465.png">

**Comment by katyedwards** [comment]
Great, thanks Cleo.
