### ISSUE TITLE
Clinician: rename menu item. 'Details and Meds'

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#37]
<img width="364" alt="screen shot 2017-07-05 at 15 20 47" src="https://user-images.githubusercontent.com/25012688/27868879-08040964-6196-11e7-860c-5a3bdeea9bfc.png">

**Comment by MollieCourtenay** [comment]
Is this something I can do through editing a template?

**Comment by katyedwards** [comment]
Both updated
