### ISSUE TITLE
Clinician: edits to details and contacts section

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#39]
+ [ ]  As a clinician, looking at a service users page, I can see a yellow box with:
- date of birth
- email 
- phone number

+ [ ] Clinicians cannot see NHS number, of home address.

<img width="364" alt="screen shot 2017-07-05 at 15 20 47" src="https://user-images.githubusercontent.com/25012688/27870327-7e88d1a6-619a-11e7-9b59-c4652ab81aa4.png">

**Comment by iteles** [comment]
This will consist of the removal of the NHS number and home address from this section.

**Comment by ghost** [comment]
This has been done, not sure when!
