### ISSUE TITLE
Replace with this logo with version with a capital S

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#4]
+ [x] as a user I see the Headscape logo not the HL one.

**Comment by MollieCourtenay** [comment]
https://www.dropbox.com/s/13nnju1mkecm8xt/headscape%20logo%202.svg.svg?dl=0
Needs to have 'Headscape Focus' in museo sans rounded font.
<img width="596" alt="screen shot 2017-07-11 at 09 57 54" src="https://user-images.githubusercontent.com/25012688/28060568-72c857c2-661f-11e7-9c84-af5eea1f19a0.png">

**Comment by MollieCourtenay** [comment]
@katbow did that SGV work ok for the logo?
Have you also added the 'Headscape Focus' title underneath the logo?
They did want this in a specific font - museo sans rounded font

Sorry had hoped India would have been able to get to this before you did to get it ready. but we've not managed it.

See attached - I've just made this; not sure if its the right size and all? if not tell me what you need. 

![headscape logo and halo-01](https://user-images.githubusercontent.com/25012688/28972190-96404e02-7926-11e7-9887-ec1cbb7f8cfb.png)

**Comment by katyedwards** [comment]
Hi @Cleop thanks for starting work on these.  Can you add an awaiting review or please test label to the issues as you finish them - I know we can't test yet, but we're using those labels to track how much is done vs. still outstanding.   Thank you!

**Comment by MollieCourtenay** [comment]
+ [ ] please can this be a bit smaller? perhaps 2/3rd of this size?

**Comment by MollieCourtenay** [comment]
See above - had already looked at this.

**Comment by katyedwards** [comment]
- [ ] Update text to HeadScape with a capital S

**Comment by MollieCourtenay** [comment]
![headscape logo and halo_capital s-01](https://user-images.githubusercontent.com/25012688/29979026-a53e1ee0-8f3b-11e7-8e19-8706c3d50c30.png)
 +[ ] replace with this logo with a capital S

**Comment by RobStallion** [comment]
![image](https://user-images.githubusercontent.com/15571853/30208124-00e3120c-948a-11e7-92bc-32f27400be3f.png)

**Comment by katyedwards** [comment]
Great thanks!
