### ISSUE TITLE
About me form 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#40]
@indiamindwave24 please can you work with Caroline, to ensure all the icons are ready to be handed over to DWYL?
As well as supplying a page mock up.

Here is my rough wireframe: 

<img width="363" alt="screen shot 2017-07-05 at 15 21 11" src="https://user-images.githubusercontent.com/25012688/27868957-4c14b22a-6196-11e7-9694-656730d3f92b.png">

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please supply all the mini About me icons

**Comment by iteles** [comment]
@katyedwards @MollieCourtenay Has the design for this been finalised? We're assuming it's going to look a lot like the top comment and you can provide the icons.

**Comment by RobStallion** [comment]
@katyedwards The styling has been started for this issue but we are still awaiting the icons. Can you provide them when you have the time? Thanks

**Comment by katyedwards** [comment]
Hi @RobStallion you already have the icons for this - they were put in last time but currently just go to a 'coming soon' page.  It's the icon for the structured teachers form which is new.

Let me know if you have any problems, but I think it should just need connecting up to the existing icon.

**Comment by RobStallion** [comment]
Hey @katyedwards. Thanks for replying so quickly. I think that we might have got our wires crossed here though 😄. 

I meant the icons at the side of each input box as shown in the above image...
![image](https://user-images.githubusercontent.com/15571853/34988913-5ae22060-fab8-11e7-8e27-0d121db520fd.png)

Sorry If I have misunderstood what you meant.

I have noticed that they are not in all of the designs for the about me page. Can you confirm if they are meant to be in the designs or not?

**Comment by katyedwards** [comment]
Ahhh sorry - am with you now - I hadn't read the previous messages

Hang on a sec...

**Comment by katyedwards** [comment]
My Early Life
![icons-oxleas_early life](https://user-images.githubusercontent.com/24604903/34989288-ebaf4766-fab9-11e7-8e27-fabc7f9dcffc.png)

**Comment by katyedwards** [comment]
My Life Events
![icons-oxleas_life events](https://user-images.githubusercontent.com/24604903/34989309-fd673f54-fab9-11e7-9d9e-2b1642f2f9ea.png)

**Comment by katyedwards** [comment]
My Hobbies
![icons-oxleas_hobbies](https://user-images.githubusercontent.com/24604903/34989328-09885eda-faba-11e7-91da-0a34a8bc73e8.png)

**Comment by katyedwards** [comment]
My School
![icons-oxleas_school](https://user-images.githubusercontent.com/24604903/34989335-1173ac30-faba-11e7-9bbe-98a2ae9f17a4.png)

**Comment by katyedwards** [comment]
Important People in my Life
![icons-oxleas_important people](https://user-images.githubusercontent.com/24604903/34989344-1b474bb8-faba-11e7-8f64-e031208a7821.png)

**Comment by katyedwards** [comment]
Things I find difficult
![icons-oxleas_difficulties](https://user-images.githubusercontent.com/24604903/34989357-254e47c4-faba-11e7-95e0-743f5fd27a7a.png)

**Comment by katyedwards** [comment]
Things I am good at
![icons-oxleas_good at](https://user-images.githubusercontent.com/24604903/34989378-3404f7d6-faba-11e7-96b6-164c3644f334.png)

**Comment by katyedwards** [comment]
Sorry - missed My Health
![icons-oxleas_medication big-04](https://user-images.githubusercontent.com/24604903/34989515-a8846376-faba-11e7-818c-e99cb042b246.png)

**Comment by katyedwards** [comment]
That should be all of them @RobStallion sorry about that!

**Comment by RobStallion** [comment]
No problem. Thanks @katyedwards

**Comment by katyedwards** [comment]
Have commented on #30 about the colour so closing this one.

Thanks!
