### ISSUE TITLE
Medication notes UI

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#41]
@indiamindwave24 please can you work with Caroline, to ensure all the icons are ready to be handed over to DWYL?
As well as supplying a page mock up.

Here are my rough wireframes: 
NB: clinicians can edit the content.
<img width="285" alt="screen shot 2017-07-11 at 14 48 09" src="https://user-images.githubusercontent.com/25012688/28071485-ff620688-6647-11e7-8686-f68c1e45e316.png">

service users can only read it.

<img width="284" alt="screen shot 2017-07-11 at 14 45 53" src="https://user-images.githubusercontent.com/25012688/28071387-ac3f3660-6647-11e7-9e50-a77fbf9f5301.png">

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please supply the mini medication icons

**Comment by MollieCourtenay** [comment]
icon for the top of the page ![icons-oxleas_medication big-05](https://user-images.githubusercontent.com/25012688/28971327-749ea7c4-7923-11e7-8a70-70156fbce1a1.png)

Icon to go before the medication FAQs. same centered position.
![icons-oxleas_faq medication](https://user-images.githubusercontent.com/25012688/28971329-7664e73a-7923-11e7-908b-16c8b4ced66f.png)

**Comment by katyedwards** [comment]
Looking good!
