### ISSUE TITLE
Remove connect to slam links in Account 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#43]

**Comment by iteles** [comment]
+ Block endpoints
+ Alter tests
+ Remove

**Comment by reddog** [comment]
@katyedwards Are these the links to go:

1. Connect with my care team and health record
2. Connect with the care team of someone I care for

**Comment by reddog** [comment]
![image](https://user-images.githubusercontent.com/151362/28260673-11fa1a7a-6ad4-11e7-8361-1d8d3d3efcfb.png)

**Comment by katyedwards** [comment]
Yep, exactly.  Just those two. 

And change the text above see issue #54

**Comment by RobStallion** [comment]
links to #51. Removes call to epjs from account controller

**Comment by katyedwards** [comment]
All looks good!
