### ISSUE TITLE
remove opportunity to sign up from the Burger 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#45]
+ [x] as a user on the Oxleas landing page, I see no sign up link / buttons.

+ [x] not in burger menu
+ [x] remove welcome message #46 
+ [x] remove mentions in About #28

**Comment by katyedwards** [comment]
@RobStallion Already an issue!

**Comment by katyedwards** [comment]
Sign up is still in the burger menu and gives an error page if you click on it.
