### ISSUE TITLE
remove Welcome to healthlocker section on landing page home page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#46]
+ [x] As a user on the landing page of Oxleas site, it is edited. 
+ [x] there is no sign up button

**Comment by reddog** [comment]
Remove central "Welcome to Heathlocker" section:

![image](https://user-images.githubusercontent.com/151362/28261815-b550529e-6ad8-11e7-8512-fd585b12a511.png)

**Comment by katyedwards** [comment]
Looks good.
