### ISSUE TITLE
redirect to given URL

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#49]
We are going to have a DNS subdomain of the headscapegreenwich.co.uk

So will be focus.headscapegreenwich.co.uk

We need the IP of the instances on the azure server that we can be point the subdomain at

**Comment by katyedwards** [comment]
Chased James today and he chased his team!

**Comment by katbow** [comment]
for this we need to know the answer to #94. It's uncertain if the ssl certificate needs to be set up site wide first before we can set it up for this particular subdomain.

**Comment by katyedwards** [comment]
Thanks, I've nudged them for an answer...

**Comment by reddog** [comment]
@MollieCourtenay The IP address of the server is 51.140.117.78 This can be used now to set up DNS for focus.headscapegreenwich.co.uk

**Comment by katyedwards** [comment]
@katbow Oxleas have got in touch just to say that he will come back to us soon on a range of things we've asked - we'll update you as soon as we hear anything on this, but if you need to get to it sooner, just go with letsencrypt.

**Comment by markwilliamfirth** [comment]
Waiting on Oxleas

@katbow @RobStallion please take a look at this one and depending on answer for Oxleas

Provide a time estimate
Get input from Tony if and when you need it

**Comment by RobStallion** [comment]
@katyedwards @reddog Do you know the current progress Oxleas have made towards setting up the subdomain focus.headscapegreenwich.co.uk? This is needed in order to get an SSL Certificate so we will need to know as soon as possible.

**Comment by katyedwards** [comment]
Our contact at Oxleas was chasing his team yesterday - I've chased him again now.  Will update you as soon as I can

**Comment by RobStallion** [comment]
@katyedwards could you please check that they have made/are making the subdomain where they registered the domain that they already have. 

They need to add an 'A' record to the DNS config

**Comment by katyedwards** [comment]
@RobStallion I was just writing you a message on the other SSL issue!

I'm gonna chase again now... can you spell out for me what we need them to do/ what we need from them...

1. They need to create the subdomain
2. They need to add an A record to the DNS config (for the subdomain)
3. We need to know where it is registered

Anything else?

**Comment by markwilliamfirth** [comment]
@katyedwards just a note to say if they're willing to give @RobStallion (or myself) temporary login detail access to their domain account we'd be able to do this for them and it would speed things up

If not, that should be all, it is a relatively simple process to create a subdomain, but note that Step 1 and 2 are the same thing. Note the main issue here is the propagation time.

**Comment by RobStallion** [comment]
Thanks @katyedwards. That looks good to me.

Just to be clear, they need to create the subdomain by putting an A record in the DNS configuration. 

Once that's done, we can set up the SSL cert because the subdomain will exist. (could take up to 36 hours for the subdomain to propagate)

**Comment by reddog** [comment]
Site is now available at http://focus.headscapegreenwich.co.uk/  Since #94 deals with the SSL certificate, are we good to close this issue @katyedwards ?

**Comment by katyedwards** [comment]
Yep all done!
