### ISSUE TITLE
Replace SLaM logo with Oxleas logo for top of logged out page.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#5]
+ [x] as a user on the Oxleas domain, I see the Oxleas logo at the top of the logged out page

**Comment by MollieCourtenay** [comment]
@indiamindwave24 please can you supply an Oxleas version of the NHS logo just like the HL SLaM one - please doubl checking we are using the right blue.

NHS
Oxleas
NHS Foundation Trust

**Comment by indiamindwave24** [comment]
[Oxleas_logo.zip](https://github.com/healthlocker/oxleas-adhd/files/1190823/Oxleas_logo.zip)
