### ISSUE TITLE
remove any connection with epjs DB

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#51]
Description left blank, so the below is edited by @iteles.

+ Carers: 1 day
  + Alter connecting as carer functionality to not verify data against ePJS but to do so through our database (assuming same data is used)
+ Clinicians: 1 day

NB. Need these to be added or edited at a later date

@RobStallion Please fill in the technical detail below on what needs to be done whilst this is still fresh in your mind.

- **Carers**
  - **care_team/room_controller.ex:8**
    - [ ] Remove call to `EPJSTeamMember` table. for a given service user this function queries `eEPJS` for all associated clinicians and forms the care team. Could possibly use the relationships table as an alternative. This will effect the clinicians_list that is returned so functions `filter_clinicians`, `filter_rooms` and `add_clinicians_to_clinician_rooms` will all have to be updated accordingly.

  - **care_team/contact_controller.ex:9**
    - [ ] Remove call to `EPJSTeamMember` table. Will use new query that would have to be created in above step.
    
  - **slam_controller**
    - [ ] Will need to update `create` function, specifically the how the `changeset` is made. This will involve editing `lib/healthlocker/slam/carer_connection & connect_carer`.
  - **slam/carer_connection**
      - [ ] update `find_epjs_user` function as it currently makes a call to `EPJSUser` table to check if user exists. May be able to replace with `users` table.
  - **slam/connect_carer**
    - [ ] will need to update `add_clinicians_to_room` as it makes call to `EPJSTeamMember` table.

- **Clinicians**
  - **account_controller**
    - [ ] Will need to update the calls to `EPJSUser` when assigning `slam_user` on line 180 in `check_slam` action. 
    - [ ] Will also need to update where `multi` is assigned on line 193. Calls function in `lib/healthlocker/slam/connect_slam`
  - **slam/connect_slam`
    - [ ] update `add_clinicians_to_room` function as it makes a call to `EPJSTeamMember` table.

- **tests** (for both)
  - [ ] all related tests will need to be updated accordingly 

**Key points**

- `Super Admin (SA)` is creating users and connecting them to one another. 

- Remove links as stated in #43. This functionality will need to be moved to when the `SA` connects users to each other.

- Update function in `lib/healthlocker/slam/care_team` as it makes call to `EPJSTeamMember` and is used in many places.

- Update `users` table to have a key of `DOB` as it is currently only stored in the `ePJS DB` and `SA` will need to use is when connecting users. 

- Check the whole repo for anywhere `ReadOnlyRepo` is mentioned.

**Comment by RobStallion** [comment]
this issue is being closed in favour of [this](https://github.com/healthlocker/healthlocker/issues/941) and [this](https://github.com/healthlocker/healthlocker/issues/954) as the approach that was originally being taken has changed.
