### ISSUE TITLE
Within Admin system: add new Staff member

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#57]
As there is no ePJS system to check user details against, these will be manually entered by the Oxleas team in an Admin area #2.

As an Oxleas team member I want to be able to add a new staff member (clinician) to the system so that I can connect them to a SU.

## Acceptance Criteria
(taken from #21)
+ [x] If I am adding a new clinician, I will have to enter their first name, last name, email address, password, job role.

### Tasks
  + [x] Create form 
  + [x] Link up to correct permissions

**Comment by katyedwards** [comment]
All seems to be working fine, thanks
