### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by iteles** [healthlocker/oxleas-adhd#68]
In order to ensure we cannot accidentally push to master, we should protect the master branch to disable direct pushing to it.

Linked to #20 and #66 

https://help.github.com/articles/about-protected-branches/

**Comment by nelsonic** [comment]
https://github.com/healthlocker/oxleas-adhd/settings/branches/master
![image](https://user-images.githubusercontent.com/194400/28617088-e4efbb00-71f6-11e7-877d-0cd87a24acbe.png)

**Comment by iteles** [comment]
Done. FYI @katbow @RobStallion
