### ISSUE TITLE
ssh public key for SLaM

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/oxleas-adhd#70]
Stuart has asked for your ssh public key so he can provision environments for Oxleas.

Can you let me know

1.  Is it the same as he was given for Oxleas?
2. If not - what is it?!

Thanks

*Given P1 label as it should be a real quick thing and I don't want to risk holding SLaM up on their side of things

**Comment by nelsonic** [comment]
@katyedwards public keys for the developers do not change. 
(_unless there was a specific reason to , in which case we would inform Stuart **immediately**, see: https://security.stackexchange.com/a/15011/117318_) 

I have emailed my public key to Stuart _twice_. ✉️  ✅ 
![image](https://user-images.githubusercontent.com/194400/28745290-783bd8a8-746d-11e7-8c87-df3d06a22a23.png)

The public keys for all 3 developers are on the `staging` server in the file:
`/home/hladmin/.ssh/authorized_keys` viewable in one place by Stuart & his team at _any_ time. 👍 

> Re-requesting the `public` key shows either a poor email organisation system (_can't find my key_)
or a _worrying_ lack of understanding of public key cryptography (_the tech that secures **everything** on the internet!_) either of which isn't great for a technology worker. 😕 
I'm _guessing_ it's the _former_ (_too many emails and stuck using MS Exchange so poor filing/searchability ... as opposed to any deliberate delaying of provisioning_)

The only time a person changes their `public` key is when they think it's been "stolen" or "compromised", in the same way that nobody changes the lock (key) to their house/front-door unless they are _reasonably sure_ they've lost their keys somewhere that a crook could identify and use the lost key to enter/invade the property.

## Background/Recommended Reading

+ Good **intro** to Public Key Cryptography for _non-technical_ people: https://medium.com/@vrypan/explaining-public-key-cryptography-to-non-geeks-f0994b3c2d5
+ More detail but still ***beginner-friendly***: http://computer.howstuffworks.com/encryption.htm/printable
+ ***Comprehensive explanation*** but a bit "**academic**" https://en.wikipedia.org/wiki/Public-key_cryptography

**Comment by MollieCourtenay** [comment]
email from STUART:  1st Aug.
Thanks for the confirmation that the developer will be Nelson and his key is the one to use. As agree the Oxleas will be with you by end of play on the 14th of August.

 @nelsonic & @iteles as you guys are away - do you need more than just Nelson's key associated to this Oxleas environment. (apologies for my ignorance here)

**Comment by iteles** [comment]
@MollieCourtenay Yes, we'll need all 3 developer keys please!
