### ISSUE TITLE
File paths for new views

### ISSUE THREAD

**Issue by harrygfox** [healthlocker/oxleas-adhd#85]
## Super Admin Logs in:

- [x] `oxleas_adhd/web/templates/users/index.html.eex`

 (see caseload/index.html.eex)

## Super admin creates new users
- [x] `oxleas_adhd/web/templates/users/new_staff.html.eex`
- [x] `oxleas_adhd/web/templates/users/new_service_user.html.eex`
- [x] `oxleas_adhd/web/templates/users/new_carer.html.eex`

- [x] `oxleas_adhd/web/templates/clinician/new.html.eex` - displayed after adding a service user. Must have some clinicians added to see how checkboxes display at bottom of page. url path is `/users/:user_id/clinician-connection/new`. Can edit form in `form.html.eex` and title in `new.html.eex`

- [x] `oxleas_adhd/web/templates/carer/new.html.eex` - display after adding a carer, used to enter details to connect to a service user
- [x] `oxleas_adhd/web/templates/carer/confirm.html.eex` - displayed after entering correct info that matches a service user

## Details and Meds
- [ ] `healthlocker/web/templates/oxleas/caseload/user/menu.html.eex` (already exists)
- [ ] `healthlocker/web/templates/oxleas/caseload/user/details.html.eex`

## Details and Meds / Medication
below: see `/diary`
- [x] `oxleas_adhdweb/templates/medication/edit.html.eex` (title only)
- [x] `oxleas_adhd/web/templates/medication/faq.html.eex`
- [x] `oxleas_adhd/web/templates/medication/form.html.eex`
- [x] `oxleas_adhd/web/templates/medication/new.html.eex` (title only)
- [x] `oxleas_adhd/web/templates/medication/show.html.eex`
See [here](https://github.com/healthlocker/oxleas-adhd/issues/15#issuecomment-320303919) for edit/new title info.

## Details and Meds / About me
- [ ] `oxleas_adhd/web/templates/about_me/edit.html.eex` (title only)
- [ ] `oxleas_adhd/web/templates/about_me/new.html.eex` (title only)
- [ ] `oxleas_adhd/web/templates/about_me/form.html.eex`

**Comment by katbow** [comment]
@harrygfox one other comment here https://github.com/healthlocker/oxleas-adhd/issues/58#issuecomment-320303455

**Comment by harrygfox** [comment]
@katbow @RobStallion I believe that it's just the `about me` stuff that's left to do - the files exist and are filled with simple text but no elems. I assume the `details` is essentially covered by the other views since these files do not exist yet. 

My final step will be to complete those `about me` views once the form elements have been included. Let me know if that's not the case and when I can work on them.

**Comment by katbow** [comment]
@harrygfox I think this is good for you to close now! The about me section is being held off on for the moment, and the other 2 that are unchecked were done/are being done in conjunction with other issues. Thanks for all your work on this 🎉  ❤️ !

**Comment by harrygfox** [comment]
Thanks @katbow and @RobStallion !
